### PR TITLE
[ENH] Revise CircleCI settings

### PR DESCRIPTION
**Pull request by oesteban**
Changes proposed in this pull request
- Try to build nipype/base in circle build, and cache it properly.

### CODE REVIEW

**Comment by oesteban** [comment]
Submitted rebuild to see if caching starts working

**Comment by satra** [comment]
@oesteban - should this be merged?

**Comment by oesteban** [comment]
@satra I'm trying to see the caching working. But no luck so far. I tried splitting the cached files, so that they are smaller. Maybe that way circle would swallow them. But I don't see any changes.

Let me trigger another build. I'll enable ssh and see if the files are there.

**Comment by satra** [comment]
@oesteban - sounds good. you could also check the total size of the cache after it's created, and we can talk to the circle folks to see if the size is the limitation.

**Comment by satra** [comment]
@oesteban - did this work?

**Comment by oesteban** [comment]
Yes, the largest tarred image is 8.5 GB. I think we can gzip it. Splitting the images was not a good idea, I just expands the tar file for each single image.

**Comment by satra** [comment]
ok i'm testing the gzipped version in the other PR.

**Comment by oesteban** [comment]
Altogether, the tar (no compression) makes 12GB

**Comment by oesteban** [comment]
I close this, follow up in #2017

**Pull request closed without merging**
