### PR TITLE
ENH: Add "GenericLabel" to antsRegistration interpolation option.

### LINKED ISSUE #3423: [ENH] Add `GenericLabel` to antsRegistration interface as MultiLabel is outdated.
From `antsRegistration` manual page:

```
 -n, --interpolation Linear
                         NearestNeighbor
                         MultiLabel[<sigma=imageSpacing>,<alpha=4.0>]
                         Gaussian[<sigma=imageSpacing>,<alpha=1.0>]
                         BSpline[<order=3>]
                         CosineWindowedSinc
                         WelchWindowedSinc
                         HammingWindowedSinc
                         LanczosWindowedSinc
                         GenericLabel[<interpolator=Linear>]
```

The `GenericLabel` option is currently missing from the input spec:
https://github.com/nipy/nipype/blob/5ac2f18ac116832d81a13f0c83e0a6aeda1457cf/nipype/interfaces/ants/registration.py#L411-L423

Additionally, `MultiLabel` is no longer recommended and `GenericLabel` is the preferred option.

Will make a PR.

### PR DESCRIPTION
**Pull request by axiezai**
## Summary
Fixes #3423, i did `make check-before-commit` but I need some help editing the docs so that the new option is reflected in the HTML. 

## List of changes proposed in this PR (pull-request)
 - Add `GenericLabel` to antsRegistration interface's interpolation option

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
The docs should auto-update.

**Comment by axiezai** [comment]
Hmm do you have any idea why `nipype/interfaces/tests/test_auto_Dcm2nii.py` got deleted by `make check-before-commit` locally?

**Comment by axiezai** [comment]
reverted that commit so the tests are all there now.

**Comment by effigies** [comment]
Thanks! Not sure why `make check-before-commit` did something weird...

**Pull request merged**
