### PR TITLE
FIX: Update pybids data directory, unbundle out-of-date numpydoc

### PR DESCRIPTION
**Pull request by effigies**
Fixes failing Travis builds that depend on sample data in pybids.

Changes proposed in this pull request
- Update pybids data directory

### CODE REVIEW

**Comment by effigies** [comment]
Getting the following error on Circle:

```
Could not import extension numpy_ext.numpydoc (exception: No module named 'sphinx.util.compat')
```

Appears that we're manually packaging an old version of numpydoc. I'm switching to the release version, to see if that fixes things. @satra let me know if there's a reason we haven't been doing this up to now.

**Comment by satra** [comment]
@satra - when nipype was created a lot of things were copied over from hacks people had implemented. i suspect this was another of those things.

**Comment by effigies** [comment]
Docs seem to build fine. Good to merge?

**Comment by oesteban** [comment]
@effigies, you were right: [sphinx 1.7.0](https://github.com/sphinx-doc/sphinx/blob/2a65ffeef5c107c19084fabdd706cdff3f52d93c/CHANGES#L204) has discontinued `sphinx.util.compat`. For nipype, upgrading numpydoc did the trick.

**Pull request merged**
