### PR TITLE
Making zenodo instructions more prominent

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by satra** [comment]
@chrisfilo - you should also take a look at the PULL_REQUEST_TEMPLATE that i added in .github

**Comment by chrisfilo** [comment]
It seems like mention of .zenodo.json is already there.

**Comment by satra** [comment]
yes - i kind of committed it without review ;) - that's why it would be good if that suffices

**Comment by chrisfilo** [comment]
Up to you.

**Pull request closed without merging**
