### PR TITLE
DOC: Add Python 2 statement to README, reference maintenance branch in CONTRIBUTING

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Ref #3113. 

## List of changes proposed in this PR (pull-request)
* Add a Python 2 statement to README
* Mention maintenance branch in CONTRIBUTING

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
This could probably be expanded, but I didn't want to bloat the CONTRIBUTING guide too much. Let me know what you think.

@emdupre @choldgraf Have you seen other repositories that are keeping a Python 2-compatible branch alive for a bit, and how they're directing people to this? A quick search through some major packages has brought up nothing.

**Comment by choldgraf** [comment]
I don't know if any specifically. I know matplotlib backports a lot of stuff but nothing that's unique to python 2. I think at this point many packages are just telling users they'll drop support soon (or already have). Maintaining a separate python 2 branch seems like something you could do if there were dedicated funding for it, but to me feels too much work with volunteer labor

**Comment by effigies** [comment]
In my mind, we won't be backporting, just accepting PRs against the `maint/1.3.x` branch for people who need to fix bugs but can't use Py3.

If it becomes a serious burden, then we can consider a hard cutoff, but it seems unlikely given the overall activity level in nipype.

**Comment by effigies** [comment]
In the absence of outrage, I'll go ahead and merge this one.

**Comment by emdupre** [comment]
I also haven't seen any other libraries with this strategy, but it makes sense to me ! :+1:

**Pull request merged**
