### PR TITLE
[FIX] Remove '=' signs from EddyQuad argument specifications

### PR DESCRIPTION
**Pull request by josephmje**
Addresses #2935

### CODE REVIEW

**Comment by effigies** [comment]
You'll need to run `make specs`.

**Comment by josephmje** [comment]
Thanks @effigies . I ran `make specs` and updated the PR.

**Comment by josephmje** [comment]
Just wanted to revisit this. Is this ok the merge now?

**Comment by effigies** [comment]
Ah, thanks for the bump. I think this looks reasonable. To be clear, this won't break older versions of `eddy_quad`?

**Comment by josephmje** [comment]
`eddy_quad` was only introduced in FSL 6.0. I've tried it on both v6.0 and v6.0.1 and it works fine

**Comment by effigies** [comment]
Sounds good. Thanks for the contribution.

**Pull request merged**
