### PR TITLE
Updated auto test files to new PEP8 changes

### PR DESCRIPTION
**Pull request by blakedewey**
Ran make check-before-commit on current master. Should be merged quickly to avoid conflicts.

### CODE REVIEW

**Comment by satra** [comment]
@blakedewey - did you update the generator? perhaps that would be the best way to ensure PEP8 compliance.

**Comment by blakedewey** [comment]
The generator was updated with the PEP8 changes. But the tests were never remade for some reason.

**Comment by miykael** [comment]
Yes, that was my mistake. I forgot to update the test files with my previous PR #1255, but corrected it with my second PEP8 PR #1264. Specifically with commit https://github.com/miykael/nipype/commit/712ab695e09dfd80b7a7dfbef242b358f2b0fdf1

**Comment by satra** [comment]
since this is ready to merge, shall we merge this and cancel the other PR? or can the two of you consolidate to a single PR?

**Comment by blakedewey** [comment]
Yes that would be great.

**Comment by miykael** [comment]
I have no problem to cancel my commit with those changes. They are anyhow the same. But the commit is part of a PR (#1264) with 18 additional commits, all correcting additional PEP8 violations.
I can revert the changes of this commit and than update everything, once this PR is merged?

**Pull request merged**
