### PR TITLE
[FIX] Ensure build fails in Circle when tests fail

### PR DESCRIPTION
**Pull request by oesteban**
(ref #1933)
- Added a dummy test that always fails

### CODE REVIEW

**Comment by oesteban** [comment]
DO NOT MERGE UNTIL THE WIP FLAG IS REMOVED FROM THE TITLE.

Thanks!!

**Comment by oesteban** [comment]
this is ready to merge 👍

**Comment by satra** [comment]
@oesteban - i merged #1977, so let's merge that with this and then create the fix.

**Comment by oesteban** [comment]
I'm fixing the documentation building: there is some indentation error in the confounds module. Once I fix that, I'll merge master in.

**Comment by oesteban** [comment]
Ok, building the docs with docker in my desktop works fine now. Also merged with master. Let's see if Circle goes through. If so this is finally ready.

**Comment by oesteban** [comment]
The segmentation fault is happening in another place (or it is different): 
```
nipype/pipeline/plugins/tests/test_callback.py::test_callback_multiproc_normal /home/travis/.travis/job_stages: line 53:  6712 Segmentation fault      (core dumped) py.test -v --doctest-modules nipype
```

**Pull request merged**
