### PR TITLE
[ENH] Improved PEP8 Compliance for interfaces/fsl

### PR DESCRIPTION
**Pull request by mgclark**
This PR improves the PEP8 compliance of interfaces/fsl and is a partial fix for Issue #597.

The initial PR includes the following:
```
File             Violations    Reduction   Remain
-------------------------------------------------
base.py          1             1   (100%)  0 
dti.py           162           162 (100%)  0
epi.py           18            18  (100%)  0
maths.py         36            34  (94%)   2
model.py         104           97  (93%)   7
preprocess.py    128           116 (91%)   12
utils.py         134           117 (87%)   17 

TOTALS --------- 583 --------- 545 (93%) - 38 ---
```

There are still some long docstring lines; wrapping them made CircleCI unhappy. Even with those outstanding, the readability of the code has been improved.

### CODE REVIEW

**Comment by oesteban** [comment]
Hi @mgclark, I'm playing around with the docker images running tests in circleCI, that's why your tests are failing here. I'll try to find a solution for this ASAP

Sorry about that.

**Comment by mgclark** [comment]
@oesteban No problem! Thanks!

**Comment by oesteban** [comment]
Hi @mgclark, could you merge with current master? If you don't have the upstream set, you could do the following in your nipype's git root:

```
git remote add upstream https://github.com/nipy/nipype.git
git fetch upstream
git checkout pep8/fsl
git merge upstream/master
```
I don't think you will have any conflicts. If so you'll need to fix them, I will assist you with that. Once everything is merged and committed, you just need to do ```git push```.

**Comment by mgclark** [comment]
@oesteban No conflicts -- thanks!

**Comment by mgclark** [comment]
Tests are passing -- this should be ready to go now.

**Pull request merged**
