### PR TITLE
[ENH] Memoize FSL version check

### PR DESCRIPTION
**Pull request by oesteban**
Same as in #2274, but for FSL

Before
```
In [1]: from nipype.interfaces import fsl

In [2]: %time fsl.Info().version()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 594 µs
Out[2]: '5.0.9'

In [3]: %time fsl.Info().version()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 255 µs
Out[3]: '5.0.9'
```

After:
```
In [1]: from nipype.interfaces import fsl

In [2]: %time fsl.Info.version()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 11.9 µs
Out[2]: '5.0.9'

In [3]: %time fsl.Info.version()
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 6.68 µs
Out[3]: '5.0.9'
```

### CODE REVIEW

**Comment by effigies** [comment]
Looks good. Assume you've tested?

**Comment by oesteban** [comment]
Running fmriprep with this patch included right now.

**Comment by oesteban** [comment]
Worked well with fmriprep. Tests passed :+1:

**Comment by effigies** [comment]
I'm :+1: for merging, but I'll let @mgxd and @satra determine the timing, since they're working on a release candidate.

**Pull request merged**
