### PR TITLE
FIX: Correctly populate output spec for ICA_AROMA

### LINKED ISSUE #2026: ICA_AROMA() not working
### Summary
The newly released version 0.13.0 has a ICA_AROMA() interface defined in the fsl module but although the AROMA is executing correctly, it is throwing an error when passing the output of a node that contains the interface of the AROMA module to another node. 
### Actual behavior

AROMA node is throwing an "NameError: global name 'outputs' is not defined
Interface ICA_AROMA failed to run" although all the files that are supposed to be generated by AROMA are already in the output directory which is specified via the input.

170516-20:56:40,957 workflow INFO:
	 Executing node a in dir: /tmp/tmppbBpxu/a
170516-20:56:40,974 workflow INFO:
	 Running: ICA_AROMA.py -den nonaggr -feat /home/debottam/Desktop/OUTPUT.feat -o /home/debottam/Desktop/OUTPUT.feat/ICA_testout/
170516-21:08:56,984 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:
170516-21:08:56,986 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:------------------------------- RUNNING ICA-AROMA ------------------------------- 
170516-21:08:56,989 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 
170516-21:08:56,992 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:
170516-21:08:57,1 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:Step 1) MELODIC
170516-21:08:57,3 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - The existing/specified MELODIC directory will be used.
170516-21:08:57,5 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - The MELODIC directory does not contain the required 'stats' folder. Mixture modeling on the Z-statistical maps will be run.
170516-21:08:57,6 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:Step 2) Automatic classification of the components
170516-21:08:57,8 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - registering the spatial maps to MNI
170516-21:08:57,10 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - extracting the CSF & Edge fraction features
170516-21:08:57,14 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - extracting the Maximum RP correlation feature
170516-21:08:57,17 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - extracting the High-frequency content feature
170516-21:08:57,18 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:  - classification
170516-21:08:57,21 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:Step 3) Data denoising
170516-21:08:57,25 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:
170516-21:08:57,28 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:----------------------------------- Finished -----------------------------------
170516-21:08:57,30 interface INFO:
	 stdout 2017-05-16T21:08:56.983846:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-2fe61b5a5821> in <module>()
----> 1 a.run()

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.pyc in run(self, updatehash)
    370                     self.inputs.get_traitsfree())
    371             try:
--> 372                 self._run_interface()
    373             except:
    374                 os.remove(hashfile_unfinished)

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.pyc in _run_interface(self, execute, updatehash)
    480         old_cwd = os.getcwd()
    481         os.chdir(self.output_dir())
--> 482         self._result = self._run_command(execute)
    483         os.chdir(old_cwd)
    484 

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.pyc in _run_command(self, execute, copyfiles)
    611                 logger.info('Running: %s' % cmd)
    612             try:
--> 613                 result = self._interface.run()
    614             except Exception as msg:
    615                 self._save_results(result, cwd)

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in run(self, **inputs)
   1080         try:
   1081             runtime = self._run_wrapper(runtime)
-> 1082             outputs = self.aggregate_outputs(runtime)
   1083             runtime.endTime = dt.isoformat(dt.utcnow())
   1084             timediff = parseutc(runtime.endTime) - parseutc(runtime.startTime)

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base.pyc in aggregate_outputs(self, runtime, needed_outputs)
   1151         """ Collate expected outputs and check for existence
   1152         """
-> 1153         predicted_outputs = self._list_outputs()
   1154         outputs = self._outputs()
   1155         if predicted_outputs:

/home/debottam/anaconda2/lib/python2.7/site-packages/nipype/interfaces/fsl/ICA_AROMA.pyc in _list_outputs(self)
    109     def _list_outputs(self):
    110         out_dir = os.path.abspath(self.inputs.out_dir)
--> 111         outputs['out_dir'] = out_dir
    112 
    113         if self.inputs.denoise_type in ('aggr', 'both'):

NameError: global name 'outputs' is not defined
Interface ICA_AROMA failed to run. 
### Expected behavior
The outputs is supposed to return the output directory containing the AROMA output
### How to replicate the behavior
FEAT is already ran on requisite images and a FEAT folder containing the FEAT files is passed to the AROMA module. An already existing  output directory is also passed.
### Script/Workflow details
 from nipype.pipeline.engine import Node
from nipype import Function
from nipype.interfaces.fsl.maths import TemporalFilter
from nipype.interfaces.fsl import ICA_AROMA
a = Node(ICA_AROMA.ICA_AROMA(),name='a')
a.inputs.feat_dir = '/home/debottam/Desktop/OUTPUT.feat'
a.inputs.out_dir = '/home/debottam/Desktop/OUTPUT.feat/ICA_testout/'
a.run()
### Platform details:

Please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`
{'nibabel_version': '2.1.0', 'sys_executable': '/home/debottam/anaconda2/bin/python', 'networkx_version': '1.11', 'numpy_version': '1.11.0', 'sys_platform': 'linux2', 'sys_version': '2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]', 'commit_source': u'installation', 'commit_hash': u'fd5b81b7c', 'pkg_path': '/home/debottam/anaconda2/lib/python2.7/site-packages/nipype', 'nipype_version': u'0.13.0', 'traits_version': '4.6.0', 'scipy_version': '0.19.0'}

### Execution environment
Jupyter-Notebook
Choose one
- Container [Tag: Bug]

### PR DESCRIPTION
**Pull request by jdkent**
Fixes #2026

Changes proposed in this pull request
added `outputs = self.output_spec().get` to _list_outputs
May or may not fix the other error message.

### CODE REVIEW

**Comment by effigies** [comment]
@jdkent Can you verify that you are able to run ICA_AROMA with this interface?

**Comment by jdkent** [comment]
@effigies Sure, what is the best way to do this? copy terminal output?

**Comment by effigies** [comment]
If you like. Just for you to verify that you can run it without errors is the main thing I'm looking for. So something like:

```Python
>>> aroma = ICA_AROMA(...)
>>> res = aroma.run()
>>> res.outputs
{'out_dir': <out_dir>, ...}
```

**Comment by satra** [comment]
and this version for a workflow execution:

```
>>> from nipype import Node
>>> aroma = Node(ICA_AROMA(...), name="icaaroma")
>>> res = aroma.run()
>>> res.result.outputs
{'out_dir': <out_dir>, ...}
```

**Comment by jdkent** [comment]
Okay, this did not fix the problem:
from @effigies's command construction, the outputs are undefined and are not in a dictionary format. I presume that @satra's command will fail to give me outputs too.
`>>> res.outputs

aggr_denoised_file = <undefined>
nonaggr_denoised_file = <undefined>
out_dir = <undefined>`

**Comment by effigies** [comment]
Can you show the full command sequence you gave? I'm surprised by that result.

**Comment by jdkent** [comment]
I'm looking at how the CommandLine interface is defined, but I can't seem to figure out what's going wrong.

Here's how I set up the command.
```
>>> import nipype.interfaces.fsl.ICA_AROMA
>>> icaaroma = nipype.interfaces.fsl.ICA_AROMA.ICA_AROMA()
>>> icaaroma.inputs.in_file='/home/james/RestingState_dev/FLANKER/inputs/func/pre_sub10_FLANKER_RPI.nii.gz'
>>> icaaroma.inputs.motion_parameters='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/mc/mcImg.par'
>>> icaaroma.inputs.mat_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/functoT1.mat'
>>> icaaroma.inputs.fnirt_warp_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/T1toMNI_warp.nii.gz'
>>> icaaroma.inputs.denoise_type='nonaggr'
>>> icaaroma.inputs.out_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout11/'
>>> icaaroma.inputs.melodic_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout/melodic.ica'
>>> res = icaaroma.run()
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:------------------------------- RUNNING ICA-AROMA ------------------------------- 
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:Step 1) MELODIC
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - The existing/specified MELODIC directory will be used.
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:Step 2) Automatic classification of the components
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - registering the spatial maps to MNI
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - extracting the CSF & Edge fraction features
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - extracting the Maximum RP correlation feature
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - extracting the High-frequency content feature
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:  - classification
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:Step 3) Data denoising
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:----------------------------------- Finished -----------------------------------
170517-15:07:43,19 interface INFO:
	 stdout 2017-05-17T15:07:43.018913:
>>> res.outputs

aggr_denoised_file = <undefined>
nonaggr_denoised_file = <undefined>
out_dir = <undefined>
```

**Comment by effigies** [comment]
Nothing's jumping out at me as to why that's not working. I might need to look with fresh eyes tomorrow. If somebody else does see something, can you help @jdkent?

**Comment by jdkent** [comment]
@effigies  I will help. Nothing is jumping out at me either, but I'll keep looking.

**Comment by jdkent** [comment]
Many apologies, the version of nipype I was using with my virtual environment wasn't the most up to date version. After squaring that away I got the correct output with @effigies code structure
```
>>> import nipype.interfaces.fsl.ICA_AROMA
>>> icaaroma = nipype.interfaces.fsl.ICA_AROMA.ICA_AROMA()
>>> icaaroma.inputs.in_file='/home/james/RestingState_dev/FLANKER/inputs/func/pre_sub10_FLANKER_RPI.nii.gz'
>>> icaaroma.inputs.motion_parameters='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/mc/mcImg.par'
>>> icaaroma.inputs.mat_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/functoT1.mat'
>>> icaaroma.inputs.fnirt_warp_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/T1toMNI_warp.nii.gz'
>>> icaaroma.inputs.denoise_type='nonaggr'
>>> icaaroma.inputs.out_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout12/'
>>> icaaroma.inputs.melodic_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout/melodic.ica'
>>> icaaroma.inputs.out_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout18/'
>>> res = icaaroma.run()
170517-17:47:22,960 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:------------------------------- RUNNING ICA-AROMA ------------------------------- 
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:Step 1) MELODIC
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - The existing/specified MELODIC directory will be used.
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:Step 2) Automatic classification of the components
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - registering the spatial maps to MNI
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - extracting the CSF & Edge fraction features
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - extracting the Maximum RP correlation feature
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - extracting the High-frequency content feature
170517-17:47:22,977 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:  - classification
170517-17:47:22,978 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:Step 3) Data denoising
170517-17:47:22,978 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:
170517-17:47:22,978 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:----------------------------------- Finished -----------------------------------
170517-17:47:22,978 interface INFO:
	 stdout 2017-05-17T17:47:22.960017:
>>> res.outputs

aggr_denoised_file = <undefined>
nonaggr_denoised_file = /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout18/denoised_func_data_nonaggr.nii.gz
out_dir = /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout18

>>> res.outputs.get(
... )
{'aggr_denoised_file': <undefined>, 'nonaggr_denoised_file': u'/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout18/denoised_func_data_nonaggr.nii.gz', 'out_dir': '/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout18'}
>>> 
```
However, I did not get the behavior expected by @satra when constructing a node. There was no result attribute, but there still was the outputs attribute. Is it because of how I imported Node?

```
>>> import nipype.interfaces.fsl.ICA_AROMA
>>> import nipype.pipeline.engine as pe
>>> icaaroma = pe.Node(nipype.interfaces.fsl.ICA_AROMA.ICA_AROMA(), name='icaaromanode')
>>> icaaroma.inputs.in_file='/home/james/RestingState_dev/FLANKER/inputs/func/pre_sub10_FLANKER_RPI.nii.gz'
>>> icaaroma.inputs.motion_parameters='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/mc/mcImg.par'
>>> icaaroma.inputs.mat_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/functoT1.mat'
>>> icaaroma.inputs.fnirt_warp_file='/home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/T1toMNI_warp.nii.gz'
>>> icaaroma.inputs.denoise_type='nonaggr'
>>> icaaroma.inputs.out_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout5/'
>>> icaaroma.inputs.melodic_dir='/home/james/RestingState_dev/FLANKER/ICA_AROMA_testout/melodic.ica'
>>> res = icaaroma.run()
170517-17:50:40,553 workflow INFO:
	 Executing node icaaromanode in dir: /tmp/tmp5fE7pL/icaaromanode
170517-17:50:40,565 workflow INFO:
	 Running: ICA_AROMA.py -den nonaggr -warp /home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/T1toMNI_warp.nii.gz -i /home/james/RestingState_dev/FLANKER/inputs/func/pre_sub10_FLANKER_RPI.nii.gz -affmat /home/james/RestingState_dev/FLANKER/BetaSeries_testout/reg/functoT1.mat -meldir /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout/melodic.ica -mc /home/james/RestingState_dev/FLANKER/BetaSeries_testout/mc/mcImg.par -o /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout5/
170517-18:02:31,726 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:
170517-18:02:31,726 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:------------------------------- RUNNING ICA-AROMA ------------------------------- 
170517-18:02:31,726 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 
170517-18:02:31,726 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:
170517-18:02:31,726 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:Step 1) MELODIC
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - The existing/specified MELODIC directory will be used.
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:Step 2) Automatic classification of the components
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - registering the spatial maps to MNI
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - extracting the CSF & Edge fraction features
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - extracting the Maximum RP correlation feature
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - extracting the High-frequency content feature
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:  - classification
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:Step 3) Data denoising
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:----------------------------------- Finished -----------------------------------
170517-18:02:31,727 interface INFO:
	 stdout 2017-05-17T18:02:31.726480:
>>> res.outputs

aggr_denoised_file = <undefined>
nonaggr_denoised_file = /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout5/denoised_func_data_nonaggr.nii.gz
out_dir = /home/james/RestingState_dev/FLANKER/ICA_AROMA_testout5

>>> res.result.outputs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'InterfaceResult' object has no attribute 'result'
```

**Comment by satra** [comment]
@jdkent - my instructions were off. i meant to say node.result.outputs. but this output looks fine.

**Pull request merged**
