### PR TITLE
STY: Black

### PR DESCRIPTION
**Pull request by effigies**
This PR runs a basic `black nipype/` command.

TODO:

* [x] Update `make specs` to format results with `black` to avoid oscillation between the old and new formats.

### CODE REVIEW

**Comment by effigies** [comment]
This might be the PR that totally breaks the validity of sorting contributions by `git-line-summary`...

**Comment by satra** [comment]
there will never be a good time to do this, i think. so we should just do it.

**Comment by effigies** [comment]
Here's the `.zenodo.py` diff after this:

```diff
diff --git a/.zenodo.json b/.zenodo.json
index 5598da914..944f3eb3a 100644
--- a/.zenodo.json
+++ b/.zenodo.json
@@ -11,14 +11,7 @@
       "orcid": "0000-0002-6533-164X"
     },
     {
-      "affiliation": "MIT",
-      "name": "Jarecka, Dorota",
-      "orcid": "0000-0003-1857-8129"
-    },
-    {
-      "affiliation": "Independent",
-      "name": "Ziegler, Erik",
-      "orcid": "0000-0003-1857-8129"
+      "name": "Burns, Christopher"
     },
     {
       "affiliation": "University of Iowa",
@@ -26,7 +19,9 @@
       "orcid": "0000-0001-9513-2660"
     },
     {
-      "name": "Burns, Christopher"
+      "affiliation": "Independent",
+      "name": "Ziegler, Erik",
+      "orcid": "0000-0003-1857-8129"
     },
     {
       "affiliation": "Klinikum rechts der Isar, TUM. ACPySS",
@@ -34,27 +29,36 @@
       "orcid": "0000-0002-6608-6885"
     },
     {
-      "name": "Hamalainen, Carlo",
-      "orcid": "0000-0001-7655-3830"
+      "affiliation": "MIT",
+      "name": "Jarecka, Dorota",
+      "orcid": "0000-0003-1857-8129"
     },
     {
-      "affiliation": "The Laboratory for Investigative Neurophysiology (The LINE), Department of Radiology and Department of Clinical Neurosciences, Lausanne, Switzerland; Center for Biomedical Imaging (CIBM), Lausanne, Switzerland",
-      "name": "Notter, Michael Philipp",
-      "orcid": "0000-0002-5866-047X"
+      "affiliation": "The University of Iowa",
+      "name": "Ellis, David Gage",
+      "orcid": "0000-0002-3718-6836"
     },
     {
       "name": "Yvernault, Benjamin"
     },
     {
-      "affiliation": "The University of Iowa",
-      "name": "Ellis, David Gage",
-      "orcid": "0000-0002-3718-6836"
+      "name": "Hamalainen, Carlo",
+      "orcid": "0000-0001-7655-3830"
+    },
+    {
+      "affiliation": "The Laboratory for Investigative Neurophysiology (The LINE), Department of Radiology and Department of Clinical Neurosciences, Lausanne, Switzerland; Center for Biomedical Imaging (CIBM), Lausanne, Switzerland",
+      "name": "Notter, Michael Philipp",
+      "orcid": "0000-0002-5866-047X"
     },
     {
       "affiliation": "Florida International University",
       "name": "Salo, Taylor",
       "orcid": "0000-0001-9813-3167"
     },
+    {
+      "affiliation": "Department of Psychology, Stanford University",
+      "name": "Waskom, Michael"
+    },
     {
       "affiliation": "MIT",
       "name": "Goncalves, Mathias",
@@ -65,50 +69,40 @@
       "name": "Jordan, Kesshi",
       "orcid": "0000-0001-6313-0580"
     },
-    {
-      "affiliation": "Department of Psychology, Stanford University",
-      "name": "Waskom, Michael"
-    },
     {
       "affiliation": "Shattuck Lab, UCLA Brain Mapping Center",
       "name": "Wong, Jason"
     },
-    {
-      "affiliation": "Developer",
-      "name": "Clark, Daniel",
-      "orcid": "0000-0002-8121-8954"
-    },
-    {
-      "name": "Loney, Fred"
-    },
     {
       "affiliation": "Department of Electrical and Computer Engineering, Johns Hopkins University",
       "name": "Dewey, Blake E",
       "orcid": "0000-0003-4554-5058"
     },
     {
-      "affiliation": "National Institute of Mental Health",
-      "name": "Nielson, Dylan M.",
-      "orcid": "0000-0003-4613-6643"
+      "name": "Madison, Cindee"
     },
     {
-      "name": "Madison, Cindee"
+      "affiliation": "Developer",
+      "name": "Clark, Daniel",
+      "orcid": "0000-0002-8121-8954"
     },
     {
-      "affiliation": "Molecular Imaging Research Center, CEA, France",
-      "name": "Bougacha, Salma"
+      "name": "Loney, Fred"
     },
     {
-      "affiliation": "Stanford University",
-      "name": "\u0106iri\u0107 , Rastko",
-      "orcid": "0000-0001-6347-7939"
+      "affiliation": "UC Berkeley",
+      "name": "Clark, Dav",
+      "orcid": "0000-0002-3982-4416"
     },
     {
-      "affiliation": "National Institutes of Health",
-      "name": "Clark, Michael G. "
+      "affiliation": "National Institute of Mental Health",
+      "name": "Nielson, Dylan M.",
+      "orcid": "0000-0003-4613-6643"
     },
     {
-      "name": "Modat, Marc"
+      "affiliation": "UC Berkeley - UCSF Graduate Program in Bioengineering",
+      "name": "Keshavan, Anisha",
+      "orcid": "0000-0003-3554-043X"
     },
     {
       "affiliation": "Mayo Clinic, Neurology, Rochester, MN, USA",
@@ -116,14 +110,16 @@
       "orcid": "0000-0002-2666-0969"
     },
     {
-      "affiliation": "UC Berkeley",
-      "name": "Clark, Dav",
-      "orcid": "0000-0002-3982-4416"
+      "name": "Modat, Marc"
     },
     {
-      "affiliation": "UC Berkeley - UCSF Graduate Program in Bioengineering",
-      "name": "Keshavan, Anisha",
-      "orcid": "0000-0003-3554-043X"
+      "affiliation": "Molecular Imaging Research Center, CEA, France",
+      "name": "Bougacha, Salma"
+    },
+    {
+      "affiliation": "CNRS LTCI, Telecom ParisTech, Universit\u00e9 Paris-Saclay",
+      "name": "Gramfort, Alexandre",
+      "orcid": "0000-0001-9791-4404"
     },
     {
       "affiliation": "Dartmouth College",
@@ -134,13 +130,17 @@
       "name": "Pinsard, Basile"
     },
     {
-      "affiliation": "CNRS LTCI, Telecom ParisTech, Universit\u00e9 Paris-Saclay",
-      "name": "Gramfort, Alexandre",
-      "orcid": "0000-0001-9791-4404"
+      "name": "Berleant, Shoshana"
     },
     {
-      "affiliation": "Concordia University",
-      "name": "Benderoff, Erin"
+      "affiliation": "Institute for Biomedical Engineering, ETH and University of Zurich",
+      "name": "Christian, Horea",
+      "orcid": "0000-0001-7037-2449"
+    },
+    {
+      "affiliation": "The University of Washington eScience Institute",
+      "name": "Rokem, Ariel",
+      "orcid": "0000-0003-0679-1985"
     },
     {
       "affiliation": "Dartmouth College: Hanover, NH, United States",
@@ -148,49 +148,49 @@
       "orcid": "0000-0003-3456-2493"
     },
     {
-      "affiliation": "Institute for Biomedical Engineering, ETH and University of Zurich",
-      "name": "Christian, Horea",
-      "orcid": "0000-0001-7037-2449"
+      "affiliation": "MIT",
+      "name": "Kaczmarzyk, Jakub",
+      "orcid": "0000-0002-5544-7577"
     },
     {
-      "name": "Berleant, Shoshana"
+      "affiliation": "Concordia University",
+      "name": "Benderoff, Erin"
     },
     {
-      "affiliation": "The Centre for Addiction and Mental Health",
-      "name": "Joseph, Michael",
-      "orcid": "0000-0002-0068-230X"
+      "affiliation": "Stanford University",
+      "name": "\u0106iri\u0107 , Rastko",
+      "orcid": "0000-0001-6347-7939"
     },
     {
-      "affiliation": "ARAMIS LAB, Brain and Spine Institute (ICM), Paris, France.",
-      "name": "Guillon, Je\u0301re\u0301my",
-      "orcid": "0000-0002-2672-7510"
+      "affiliation": "INRIA",
+      "name": "Varoquaux, Gael",
+      "orcid": "0000-0003-1076-5122"
     },
     {
-      "affiliation": "The University of Washington eScience Institute",
-      "name": "Rokem, Ariel",
-      "orcid": "0000-0003-0679-1985"
+      "name": "Moloney, Brendan"
     },
     {
-      "affiliation": "Indiana University, IN, USA",
-      "name": "Koudoro, Serge"
+      "affiliation": "Montreal Neurological Institute and Hospital",
+      "name": "DuPre, Elizabeth",
+      "orcid": "0000-0003-1358-196X"
     },
     {
-      "affiliation": "Montreal Neurological Institute and Hospital",
-      "name": "Markello, Ross",
-      "orcid": "0000-0003-1057-1336"
+      "affiliation": "Indiana University, IN, USA",
+      "name": "Koudoro, Serge"
     },
     {
-      "affiliation": "Montreal Neurological Institute and Hospital",
-      "name": "DuPre, Elizabeth",
-      "orcid": "0000-0003-1358-196X"
+      "affiliation": "National Institutes of Health",
+      "name": "Clark, Michael G. "
     },
     {
-      "affiliation": "MIT",
-      "name": "Kaczmarzyk, Jakub",
-      "orcid": "0000-0002-5544-7577"
+      "affiliation": "Athena EPI, Inria Sophia-Antipolis",
+      "name": "Wassermann, Demian",
+      "orcid": "0000-0001-5194-6056"
     },
     {
-      "name": "Moloney, Brendan"
+      "affiliation": "The Centre for Addiction and Mental Health",
+      "name": "Joseph, Michael",
+      "orcid": "0000-0002-0068-230X"
     },
     {
       "affiliation": "UC San Diego",
@@ -198,14 +198,17 @@
       "orcid": "0000-0002-7782-0790"
     },
     {
-      "affiliation": "INRIA",
-      "name": "Varoquaux, Gael",
-      "orcid": "0000-0003-1076-5122"
+      "affiliation": "ARAMIS LAB, Brain and Spine Institute (ICM), Paris, France.",
+      "name": "Guillon, Je\u0301re\u0301my",
+      "orcid": "0000-0002-2672-7510"
     },
     {
-      "affiliation": "Athena EPI, Inria Sophia-Antipolis",
-      "name": "Wassermann, Demian",
-      "orcid": "0000-0001-5194-6056"
+      "affiliation": "Montreal Neurological Institute and Hospital",
+      "name": "Markello, Ross",
+      "orcid": "0000-0003-1057-1336"
+    },
+    {
+      "name": "Buchanan, Colin"
     },
     {
       "affiliation": "Otto-von-Guericke-University Magdeburg, Germany",
@@ -213,58 +216,42 @@
       "orcid": "0000-0001-6398-6370"
     },
     {
-      "affiliation": "Vrije Universiteit, Amsterdam",
-      "name": "de Hollander, Gilles",
-      "orcid": "0000-0003-1988-5091"
+      "name": "Tungaraza, Rosalia"
     },
     {
-      "name": "Mordom, David"
+      "affiliation": "Nathan s Kline institute for psychiatric research",
+      "name": "Sikka, Sharad"
     },
     {
       "affiliation": "Australian eHealth Research Centre, Commonwealth Scientific and Industrial Research Organisation; University of Queensland",
       "name": "Gillman, Ashley",
       "orcid": "0000-0001-9130-1092"
     },
-    {
-      "name": "Buchanan, Colin"
-    },
-    {
-      "affiliation": "Max Planck Institute for Human Cognitive and Brain Sciences, Leipzig, Germany.",
-      "name": "Tabas, Alejandro",
-      "orcid": "0000-0002-8643-1543"
-    },
-    {
-      "name": "Tungaraza, Rosalia"
-    },
     {
       "affiliation": "California Institute of Technology",
       "name": "Pauli, Wolfgang M.",
       "orcid": "0000-0002-0966-0254"
     },
     {
-      "affiliation": "Nathan s Kline institute for psychiatric research",
-      "name": "Sikka, Sharad"
+      "affiliation": "Vrije Universiteit, Amsterdam",
+      "name": "de Hollander, Gilles",
+      "orcid": "0000-0003-1988-5091"
     },
     {
       "name": "Forbes, Jessica"
     },
-    {
-      "affiliation": "University College London",
-      "name": "Mancini, Matteo",
-      "orcid": "0000-0001-7194-4568"
-    },
     {
       "affiliation": "Duke University",
       "name": "Iqbal, Shariq",
       "orcid": "0000-0003-2766-8425"
     },
     {
-      "name": "Schwartz, Yannick"
+      "name": "Mordom, David"
     },
     {
-      "affiliation": "University of Washington",
-      "name": "Richie-Halford, Adam",
-      "orcid": "0000-0001-9276-9084"
+      "affiliation": "University College London",
+      "name": "Mancini, Matteo",
+      "orcid": "0000-0001-7194-4568"
     },
     {
       "affiliation": "University College London",
@@ -275,33 +262,33 @@
       "name": "Dubois, Mathieu"
     },
     {
-      "affiliation": "Holland Bloorview Kids Rehabilitation Hospital",
-      "name": "Tilley II, Steven",
-      "orcid": "0000-0003-4853-5082"
+      "name": "Schwartz, Yannick"
     },
     {
       "affiliation": "Child Mind Institute",
       "name": "Frohlich, Caroline"
     },
+    {
+      "affiliation": "Max Planck Institute for Human Cognitive and Brain Sciences, Leipzig, Germany.",
+      "name": "Tabas, Alejandro",
+      "orcid": "0000-0002-8643-1543"
+    },
     {
       "affiliation": "University of Iowa",
       "name": "Welch, David"
     },
     {
-      "affiliation": "Florida International University",
-      "name": "Bottenhorn, Katherine",
-      "orcid": "0000-0002-7796-8795"
+      "affiliation": "University of Washington",
+      "name": "Richie-Halford, Adam",
+      "orcid": "0000-0001-9276-9084"
     },
     {
       "name": "Watanabe, Aimi"
     },
     {
-      "affiliation": "Research Group Neuroanatomy and Connectivity, Max Planck Institute for Human Cognitive and Brain Sciences, Leipzig, Germany",
-      "name": "Huntenburg, Julia M.",
-      "orcid": "0000-0003-0579-9811"
-    },
-    {
-      "name": "Cumba, Chad"
+      "affiliation": "Holland Bloorview Kids Rehabilitation Hospital",
+      "name": "Tilley II, Steven",
+      "orcid": "0000-0003-4853-5082"
     },
     {
       "affiliation": "SRI International",
@@ -309,31 +296,30 @@
       "orcid": "0000-0003-1099-3328"
     },
     {
-      "affiliation": "University of Texas at Austin",
-      "name": "De La Vega, Alejandro",
-      "orcid": "0000-0001-9062-3778"
+      "affiliation": "Research Group Neuroanatomy and Connectivity, Max Planck Institute for Human Cognitive and Brain Sciences, Leipzig, Germany",
+      "name": "Huntenburg, Julia M.",
+      "orcid": "0000-0003-0579-9811"
     },
     {
       "affiliation": "University College London",
       "name": "Eshaghi, Arman",
       "orcid": "0000-0002-6652-3512"
     },
-    {
-      "name": "Ginsburg, Daniel"
-    },
     {
       "affiliation": "National University Singapore",
       "name": "Schaefer, Alexander",
       "orcid": "0000-0001-6488-4739"
     },
     {
-      "affiliation": "Harvard University - Psychology",
-      "name": "Kastman, Erik",
-      "orcid": "0000-0001-7221-9042"
+      "name": "Ginsburg, Daniel"
     },
     {
-      "name": "Heinsfeld, Anibal S\u00f3lon",
-      "orcid": "0000-0002-2050-0614"
+      "affiliation": "Florida International University",
+      "name": "Bottenhorn, Katherine",
+      "orcid": "0000-0002-7796-8795"
+    },
+    {
+      "name": "Cumba, Chad"
     },
     {
       "affiliation": "Washington University in St Louis",
@@ -341,9 +327,13 @@
       "orcid": "0000-0001-6392-6634"
     },
     {
-      "affiliation": "University of Zurich",
-      "name": "Liem, Franz",
-      "orcid": "0000-0003-0646-4810"
+      "name": "Heinsfeld, Anibal S\u00f3lon",
+      "orcid": "0000-0002-2050-0614"
+    },
+    {
+      "affiliation": "Harvard University - Psychology",
+      "name": "Kastman, Erik",
+      "orcid": "0000-0001-7221-9042"
     },
     {
       "name": "Kent, James"
@@ -352,11 +342,6 @@
       "affiliation": "UniversityHospital Heidelberg, Germany",
       "name": "Kleesiek, Jens"
     },
-    {
-      "affiliation": "NIMH IRP",
-      "name": "Lee, John A.",
-      "orcid": "0000-0001-5884-4247"
-    },
     {
       "name": "Erickson, Drew"
     },
@@ -365,28 +350,37 @@
       "name": "Giavasis, Steven"
     },
     {
-      "name": "Correa, Carlos"
+      "name": "Ghayoor, Ali"
     },
     {
-      "name": "Ghayoor, Ali"
+      "affiliation": "University of Zurich",
+      "name": "Liem, Franz",
+      "orcid": "0000-0003-0646-4810"
+    },
+    {
+      "affiliation": "University of Texas at Austin",
+      "name": "De La Vega, Alejandro",
+      "orcid": "0000-0001-9062-3778"
     },
     {
       "name": "K\u00fcttner, Ren\u00e9"
     },
+    {
+      "name": "Millman, Jarrod"
+    },
     {
       "affiliation": "Neurospin/Unicog/Inserm/CEA",
       "name": "Perez-Guevara, Martin Felipe",
       "orcid": "0000-0003-4497-861X"
     },
     {
-      "name": "Millman, Jarrod"
+      "affiliation": "NIMH IRP",
+      "name": "Lee, John A.",
+      "orcid": "0000-0001-5884-4247"
     },
     {
       "name": "Zhou, Dale"
     },
-    {
-      "name": "Blair, Ross"
-    },
     {
       "name": "Haselgrove, Christian"
     },
@@ -394,28 +388,11 @@
       "name": "Renfro, Mandy"
     },
     {
-      "affiliation": "The University of Sydney",
-      "name": "Liu, Siqi"
-    },
-    {
-      "affiliation": "University of Pennsylvania",
-      "name": "Kahn, Ari E.",
-      "orcid": "0000-0002-2127-0507"
-    },
-    {
-      "affiliation": "Korea Advanced Institute of Science and Technology",
-      "name": "Kim, Sin",
-      "orcid": "0000-0003-4652-3758"
-    },
-    {
-      "affiliation": "University College London",
-      "name": "P\u00e9rez-Garc\u00eda, Fernando",
-      "orcid": "0000-0001-9090-3024"
+      "name": "Correa, Carlos"
     },
     {
-      "affiliation": "Department of Psychology, Stanford University",
-      "name": "Triplett, William",
-      "orcid": "0000-0002-9546-1306"
+      "affiliation": "The University of Sydney",
+      "name": "Liu, Siqi"
     },
     {
       "affiliation": "MPI CBS Leipzig, Germany",
@@ -430,29 +407,19 @@
       "name": "Hallquist, Michael"
     },
     {
-      "affiliation": "Yale University; New Haven, CT, United States",
-      "name": "Sisk, Lucinda M.",
-      "orcid": "0000-0003-4900-9770"
-    },
-    {
-      "affiliation": "Donders Institute for Brain, Cognition and Behavior, Center for Cognitive Neuroimaging",
-      "name": "Chetverikov, Andrey",
-      "orcid": "0000-0003-2767-6310"
-    },
-    {
-      "affiliation": "GIGA Institute",
-      "name": "Grignard, Martin",
-      "orcid": "0000-0001-5549-1861"
+      "affiliation": "University of Pennsylvania",
+      "name": "Kahn, Ari E.",
+      "orcid": "0000-0002-2127-0507"
     },
     {
-      "affiliation": "Dartmouth College",
-      "name": "Ma, Feilong",
-      "orcid": "0000-0002-6838-3971"
+      "affiliation": "1 McGill Centre for Integrative Neuroscience (MCIN), Ludmer Centre for Neuroinformatics and Mental Health, Montreal Neurological Institute (MNI), McGill University, Montr\u00e9al, 3801 University Street, WB-208, H3A 2B4, Qu\u00e9bec, Canada. 2 University of Lyon, CNRS, INSERM, CREATIS., Villeurbanne, 7, avenue Jean Capelle, 69621, France.",
+      "name": "Glatard, Tristan",
+      "orcid": "0000-0003-2620-5883"
     },
     {
-      "affiliation": "Department of Neuropsychiatry, University of Pennsylvania",
-      "name": "Cieslak, Matthew",
-      "orcid": "0000-0002-1931-4734"
+      "affiliation": "Department of Psychology, Stanford University",
+      "name": "Triplett, William",
+      "orcid": "0000-0002-9546-1306"
     },
     {
       "affiliation": "INRIA-Saclay, Team Parietal",
@@ -463,15 +430,17 @@
       "name": "Salvatore, John"
     },
     {
-      "name": "Park, Anne"
+      "affiliation": "University College London",
+      "name": "P\u00e9rez-Garc\u00eda, Fernando",
+      "orcid": "0000-0001-9090-3024"
     },
     {
-      "affiliation": "1 McGill Centre for Integrative Neuroscience (MCIN), Ludmer Centre for Neuroinformatics and Mental Health, Montreal Neurological Institute (MNI), McGill University, Montr\u00e9al, 3801 University Street, WB-208, H3A 2B4, Qu\u00e9bec, Canada. 2 University of Lyon, CNRS, INSERM, CREATIS., Villeurbanne, 7, avenue Jean Capelle, 69621, France.",
-      "name": "Glatard, Tristan",
-      "orcid": "0000-0003-2620-5883"
+      "affiliation": "Dartmouth College",
+      "name": "Ma, Feilong",
+      "orcid": "0000-0002-6838-3971"
     },
     {
-      "name": "Poldrack, Russell"
+      "name": "Park, Anne"
     },
     {
       "affiliation": "Child Mind Institute",
@@ -482,30 +451,34 @@
       "name": "Hinds, Oliver"
     },
     {
-      "affiliation": "TIB \u2013 Leibniz Information Centre for Science and Technology and University Library, Hannover, Germany",
-      "name": "Leinweber, Katrin",
-      "orcid": "0000-0001-5135-5758"
-    },
-    {
-      "name": "Inati, Souheil"
+      "name": "Poldrack, Russell"
     },
     {
       "affiliation": "Boston University",
       "name": "Perkins, L. Nathan"
     },
     {
-      "affiliation": "University of Newcastle, Australia",
-      "name": "Cooper, Gavin",
-      "orcid": "0000-0002-7186-5293"
+      "affiliation": "Korea Advanced Institute of Science and Technology",
+      "name": "Kim, Sin",
+      "orcid": "0000-0003-4652-3758"
     },
     {
-      "name": "Mattfeld, Aaron"
+      "affiliation": "Donders Institute for Brain, Cognition and Behavior, Center for Cognitive Neuroimaging",
+      "name": "Chetverikov, Andrey",
+      "orcid": "0000-0003-2767-6310"
     },
     {
-      "name": "Matsubara, K"
+      "name": "Inati, Souheil"
     },
     {
-      "name": "Noel, Maxime"
+      "affiliation": "Department of Neuropsychiatry, University of Pennsylvania",
+      "name": "Cieslak, Matthew",
+      "orcid": "0000-0002-1931-4734"
+    },
+    {
+      "affiliation": "GIGA Institute",
+      "name": "Grignard, Martin",
+      "orcid": "0000-0001-5549-1861"
     },
     {
       "affiliation": "University of Amsterdam",
@@ -513,8 +486,14 @@
       "orcid": "0000-0001-8972-204X"
     },
     {
-      "affiliation": "Institute of Imaging & Computer Vision, RWTH Aachen University, Germany",
-      "name": "Weninger, Leon"
+      "affiliation": "Yale University; New Haven, CT, United States",
+      "name": "Sisk, Lucinda M.",
+      "orcid": "0000-0003-4900-9770"
+    },
+    {
+      "affiliation": "TIB \u2013 Leibniz Information Centre for Science and Technology and University Library, Hannover, Germany",
+      "name": "Leinweber, Katrin",
+      "orcid": "0000-0001-5135-5758"
     },
     {
       "affiliation": "University of Pennsylvania",
@@ -522,56 +501,35 @@
       "orcid": "0000-0003-2077-3070"
     },
     {
-      "name": "Cheung, Brian"
+      "name": "Matsubara, K"
     },
     {
       "name": "Urchs, Sebastian"
     },
     {
-      "affiliation": "Dept of Medical Biophysics, Univeristy of Western Ontario",
-      "name": "Stanley, Olivia"
-    },
-    {
-      "affiliation": "Department of Psychology, Stanford University; Parietal, INRIA",
-      "name": "Durnez, Joke",
-      "orcid": "0000-0001-9030-2202"
-    },
-    {
-      "affiliation": "Leibniz Institute for Neurobiology",
-      "name": "Stadler, J\u00f6rg",
-      "orcid": "0000-0003-4313-129X"
-    },
-    {
-      "affiliation": "CNRS, UMS3552 IRMaGe",
-      "name": "Condamine, Eric",
-      "orcid": "0000-0002-9533-3769"
-    },
-    {
-      "affiliation": "Technische Universit\u00e4t Dresden, Faculty of Medicine, Department of Child and Adolescent Psychiatry",
-      "name": "Geisler, Daniel",
-      "orcid": "0000-0003-2076-5329"
+      "name": "Blair, Ross"
     },
     {
       "affiliation": "The University of Texas at Austin",
       "name": "Floren, Andrew",
       "orcid": "0000-0003-3618-2056"
     },
+    {
+      "name": "Mattfeld, Aaron"
+    },
     {
       "affiliation": "Institute of Neuroinformatics, ETH/University of Zurich",
       "name": "Gerhard, Stephan",
       "orcid": "0000-0003-4454-6171"
     },
     {
-      "affiliation": "Technical University Munich",
-      "name": "Molina-Romero, Miguel",
-      "orcid": "0000-0001-8054-0426"
+      "affiliation": "University of Newcastle, Australia",
+      "name": "Cooper, Gavin",
+      "orcid": "0000-0002-7186-5293"
     },
     {
       "name": "Haehn, Daniel"
     },
-    {
-      "name": "Weinstein, Alejandro"
-    },
     {
       "name": "Tambini, Arielle"
     },
@@ -580,24 +538,28 @@
       "name": "Broderick, William",
       "orcid": "0000-0002-8999-9003"
     },
-    {
-      "name": "Rothmei, Simon"
-    },
     {
       "affiliation": "University of Helsinki",
       "name": "Andberg, Sami Kristian",
       "orcid": "0000-0002-5650-3964"
     },
     {
-      "name": "Khanuja, Ranjeet"
+      "name": "Noel, Maxime"
     },
     {
-      "affiliation": "National Institute on Aging, Baltimore, MD, USA",
-      "name": "Bilgel, Murat",
-      "orcid": "0000-0001-5042-7422"
+      "affiliation": "Department of Psychology, Stanford University; Parietal, INRIA",
+      "name": "Durnez, Joke",
+      "orcid": "0000-0001-9030-2202"
     },
     {
-      "name": "Schlamp, Kai"
+      "affiliation": "Leibniz Institute for Neurobiology",
+      "name": "Stadler, J\u00f6rg",
+      "orcid": "0000-0003-4313-129X"
+    },
+    {
+      "affiliation": "CNRS, UMS3552 IRMaGe",
+      "name": "Condamine, Eric",
+      "orcid": "0000-0002-9533-3769"
     },
     {
       "affiliation": "CEA",
@@ -605,15 +567,27 @@
       "orcid": "0000-0002-1242-8990"
     },
     {
-      "name": "Tarbert, Claire"
+      "affiliation": "Technische Universit\u00e4t Dresden, Faculty of Medicine, Department of Child and Adolescent Psychiatry",
+      "name": "Geisler, Daniel",
+      "orcid": "0000-0003-2076-5329"
+    },
+    {
+      "name": "Weinstein, Alejandro"
     },
     {
       "name": "Harms, Robbert"
     },
+    {
+      "name": "Khanuja, Ranjeet"
+    },
     {
       "affiliation": "University of Illinois Urbana Champaign",
       "name": "Sharp, Paul"
     },
+    {
+      "affiliation": "Dept of Medical Biophysics, Univeristy of Western Ontario",
+      "name": "Stanley, Olivia"
+    },
     {
       "name": "Crusoe, Michael R.",
       "orcid": "0000-0002-2961-9670"
@@ -640,10 +614,6 @@
       "name": "Lerma-Usabiaga, Garikoitz",
       "orcid": "0000-0001-9800-4816"
     },
-    {
-      "affiliation": "Vrije Universiteit Amsterdam",
-      "name": "Ort, Eduard"
-    },
     {
       "name": "Shachnev, Dmitry"
     },
@@ -652,6 +622,12 @@
       "name": "McNamee, Daniel",
       "orcid": "0000-0001-9928-4960"
     },
+    {
+      "name": "Tarbert, Claire"
+    },
+    {
+      "name": "Cheung, Brian"
+    },
     {
       "affiliation": "University of Pittsburgh",
       "name": "Meyers, Benjamin",
@@ -665,6 +641,30 @@
     {
       "name": "Davison, Andrew"
     },
+    {
+      "affiliation": "Institute of Imaging & Computer Vision, RWTH Aachen University, Germany",
+      "name": "Weninger, Leon"
+    },
+    {
+      "affiliation": "Technical University Munich",
+      "name": "Molina-Romero, Miguel",
+      "orcid": "0000-0001-8054-0426"
+    },
+    {
+      "name": "Rothmei, Simon"
+    },
+    {
+      "affiliation": "National Institute on Aging, Baltimore, MD, USA",
+      "name": "Bilgel, Murat",
+      "orcid": "0000-0001-5042-7422"
+    },
+    {
+      "name": "Schlamp, Kai"
+    },
+    {
+      "affiliation": "Vrije Universiteit Amsterdam",
+      "name": "Ort, Eduard"
+    },
     {
       "name": "Lai, Jeff"
     },
```

**Comment by effigies** [comment]
I'll note that I have not reformatted `examples/`, which can be done in [niflows/nipype1-examples](https://github.com/niflows/nipype1-examples) if desired. No need to add a new diff to worry about between here and there.

**Comment by effigies** [comment]
Merging just to get this in. We can figure out if we want to switch Zenodo contribution estimates to commits in some other PR.

**Pull request merged**
