### PR TITLE
DOC:add instructions to install; fix doc build for python 3

### PR DESCRIPTION
**Pull request by shoshber**
small changes to start contributing!

### CODE REVIEW

**Comment by satra** [comment]
@shoshber - welcome to nipype.

i was recently told that the install instructions are not very evident for a lay person. since you are new to nipype, and editing the file in this PR, could you please take a look?

**Comment by shoshber** [comment]
@satra aye, that is exactly what I'm doing! Maybe not for a layperson, but I can provide perspective from someone who is new to the project.

**Comment by shoshber** [comment]
I was planning to add clarifications to the install documentation in another pull request, but I can do it in this one--is that what you are asking?

**Comment by satra** [comment]
@shoshber - since i saw an `install.rst` change, i thought it could be done with this. but having a separate PR for it would be good.

**Comment by shoshber** [comment]
I'm not done testing my installation of nipype yet, but here are my thoughts so far:
1. nibabel 2.0.1 is already in nipype's requirements.txt file. Why do the instructions say to install it separately?
2. Setting up my development environment to build the documentation was unexpectedly difficult. Some ideas to help it go more smoothly for the next person: a) document packages that are required for development, say, in a file called requirements-developer.txt (by analogy to requirements.txt). sphinx, graphviz would be in the file. b) build documentation testing into circleci to prevent accidental commits of breaking changes

I updated install.rst with some clarifications/additional instructions. I'll add it to this pull request as soon as it finishes building.

Shoshana

**Comment by chrisfilo** [comment]
1. `pip install nipype` should automatically install nibabel if it's not present. There is no need to install it manually. Maybe we should remove all dependencies that are installed automatically? They only confuse users.

1. Documentation is already built and tested for error on CircleCI. See https://github.com/nipy/nipype/blob/master/circle.yml#L49

**Comment by mwaskom** [comment]
> There is no need to install it manually. Maybe we should remove all dependencies that are installed automatically? They only confuse users.

I think it's good to know what kind of dependencies a package has, though I agree it should be made clear what pip will take care of.

**Comment by shoshber** [comment]
1. Yeah, the Mac OS X instructions make it seem like you must install nibabel separately. I'll clarify that in the instructions.
2. That's odd--the numpy doc would not build in python 3 until I made the changes in the commit. I'm not versed enough in circleci to check--perhaps it is only checking the build for python 2?

**Pull request merged**
