### PR TITLE
REL: 1.4.0

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Prep for 1.4.0, for immediate release, pending completion.

Open question: Should we move from `git-line-summary` to `git shortlog` for determining .zenodo ordering? With #3096, the line summary became:

```
$ head -n 13 line-contributors.txt

 project  : nipype
 lines    :   298318
 authors  :
 109691 Oscar Esteban                       36.8%
 67391 Christopher J. Markiewicz            22.6%
 53863 Satrajit Ghosh                       18.1%
 10441 Krzysztof J. Gorgolewski             3.5%
 3841 Christopher Burns                     1.3%
 3836 Hans Johnson                          1.3%
 3828 Erik Ziegler                          1.3%
 3650 Alexandre M. Savio                    1.2%
 3458 Dorota Jarecka                        1.2%
```

Shortlog:

```
$ git shortlog -ns | head   
  3308	Satrajit Ghosh
  1968	Krzysztof J. Gorgolewski
  1810	Oscar Esteban
  1063	Christopher J. Markiewicz
   464	Christopher Burns
   383	Mathias Goncalves
   248	Dorota Jarecka
   247	Erik Ziegler
   235	Shoshana Berleant
   202	David Ellis
```

## Release checklist

* [x] Merge pending PRs
  * [x] #3099
  * [x] #3115
* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py` and `doc/conf.py`
* [x] Update `doc/documentation.rst` with previous releases
* [x] Check conda-forge feedstock build (conda-forge/nipype-feedstock#61)
* [x] Tutorial tests (https://circleci.com/workflow-run/34220e20-d2cd-4bc8-b45f-c83aa0a603e1)

## Uncredited authors

The following authors have contributed, but not added themselves to the [`.zenodo.json`](https://github.com/nipy/nipype/blob/master/.zenodo.json) file. If you would like to be an author on Zenodo releases, please add yourself or comment with your preferred publication name, affiliation and [ORCID](https://orcid.org/). If you would like to stop being spammed whenever I'm the one doing releases, let me know, and I'll add you to a blacklist.

No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Niklas Förster (@niklasfoe)
No entry to sort: Kirstie Whitaker (@KirstieJane)
No entry to sort: hstojic (@hstojic)
No entry to sort: Jonathan R. Williford (@williford)
No entry to sort: Abel González (@abelalez)
No entry to sort: Victor Férat (@vferat)
No entry to sort: Kevin Sitek (@sitek)

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
I personally vote for moving to commit ordering instead of line ordering. Mass refactors and style updates have distorted line ordering.

Any objections?

**Comment by satra** [comment]
no system is perfect - i'm fine with whichever order. 

perhaps something to consider in the future is to emphasize more recent contributors (for example between minor releases 1.3.x- 1.2.last), and everyone in major releases.

**Comment by oesteban** [comment]
No system is perfect, either way is fine by me.

**Comment by effigies** [comment]
Spent a few minutes trying to switch to commit counts, but it's dropping some entries, and I don't have the time to debug right now. So we'll leave at line counts for this release. When I fix up the script, I can submit a proper PR.

This all good? I made a couple changes in `info.py` that I think were missed by the Python 2 PR, but if someone wants to double-check, I'd appreciate it.

**Comment by satra** [comment]
looks good.

**Comment by effigies** [comment]
Also dropping [funcsigs](https://funcsigs.readthedocs.io/en/0.4/).

Will merge and release on pass.

**Pull request merged**
