### PR TITLE
ENH: ANTs JointFusion with nosetests

### PR DESCRIPTION
**Pull request by dmwelch**
ENH: ANTs JointFusion wrapping

### CODE REVIEW

**Comment by satra** [comment]
@dmwelch - is this different from hans' pull-request? in which case could you or @hjmjohnson please close that one. also could you please add an updated CHANGES file.

**Comment by dmwelch** [comment]
@satra done.

**Comment by dmwelch** [comment]
@satra 1 build is failing with --site-mirror (looks like an internal Travis error).

**Comment by satra** [comment]
restarted it.

**Pull request merged**
