### PR TITLE
[REF,FIX] Revision of the resource monitor

### PR DESCRIPTION
**Pull request by oesteban**
- [x] Allow to reuse a resource monitor file (e.g. when we reuse a partially cached work directory), with accompanying new nipype option.
- [x] Add a new `[monitoring]` section to the Nipype config file, simplified option names and updated option deprecation logic to allow for new sections. 
- [x] Allow for changing the default summary file with all the profiling traces.

### CODE REVIEW

**Comment by oesteban** [comment]
Tests passing https://circleci.com/gh/oesteban/nipype/714

**Comment by mgxd** [comment]
Are we trying to get this in for `0.14`? If so, ping @satra for review

**Comment by oesteban** [comment]
Yes, this would be nice to have in 0.14

**Comment by oesteban** [comment]
@satra, this would be the last thing before releasing 0.14.0 - isn't it?

**Pull request merged**
