### PR TITLE
Add nipype_crash_search script

### PR DESCRIPTION
**Pull request by alexsavio**
This is a script to search through a log folder for regular expressions in the tracebacks of the .pklz files.

Is it useful?

### CODE REVIEW

**Comment by satra** [comment]
thanks @alexsavio - for now i think this is fine. in the future i'd like to move this to a database search to speed things up.

**Comment by satra** [comment]
could you please update the CHANGES file and add some documentation (perhaps at the same place as nipype_display_crash)?

**Comment by alexsavio** [comment]
Please let me know if that is ok.

**Comment by satra** [comment]
@alexsavio - something weird is happening with this merge (there are too many files included that are already in master). can you close this pull request and make a change on top of current master and send?

**Comment by alexsavio** [comment]
I am sorry, yes, I still don't know how to deal with rebase/merge... I will create a new PR.

**Comment by alexsavio** [comment]
Here it is: #1438

**Pull request closed without merging**
