### PR TITLE
New interfaces

### PR DESCRIPTION
**Pull request by dclark87**
Added new afni interfaces for: 3dECM, 3dDegreeCentrality, 3dLFCD, 3dClipLevel, 3dmask_tool, and 3dSeg as well as their unit tests

### CODE REVIEW

**Comment by dclark87** [comment]
We need to add a couple of corrections here. @sgiavasis and I will let you guys know when these can be fully pulled in

**Comment by chrisfilo** [comment]
Ok. Thanks for the update.

**Comment by dclark87** [comment]
@chrisfilo - This is all patched up and ready now

**Comment by dclark87** [comment]
@chrisfilo - any thoughts on this? Does this look good to merge?

**Comment by chrisfilo** [comment]
Could you list the new interfaces in CHANGES file? Otherwise looks good.

**Comment by dclark87** [comment]
Where in CHANGES? Here? https://github.com/fcp-indi/nipype/blob/new_interfaces/CHANGES#L34

**Comment by chrisfilo** [comment]
That's the one! This way users can see what's new - it get's rendered here:
http://nipy.org/nipype/changes.html

**Pull request merged**
