### PR TITLE
FIX: import error in workflow export

### PR DESCRIPTION
**Pull request by blakedewey**
Import the pickle module, which is required for workflow export
function.

### CODE REVIEW

**Comment by blakedewey** [comment]
I think the CI failure is due to the new docker setup. Not this PR.

**Comment by satra** [comment]
@oesteban - can you take a look at this?

**Comment by oesteban** [comment]
@satra sure

**Comment by yarikoptic** [comment]
clearly, this is a fix to the issue where pickle module is used but not imported... not to piss anyone off but to progress the science, I will merge the beast.  I hope no hurt feelings.

**Pull request merged**
