### PR TITLE
RF: do not require testing harnesses for regular usage

### PR DESCRIPTION
**Pull request by yarikoptic**
continuation to #2850 , I guess awaiting on verdict from #2853  as well

### CODE REVIEW

**Comment by yarikoptic** [comment]
additional note/motivation is that pytest >= 3.6 cannot even be satisfied on stable Debian/Ubuntus (e.g. debian stretch/stable has 3.0.6).

**Comment by yarikoptic** [comment]
@oesteban do you remember "why?" (ref: a4dfe7e6a2ec78ba9cea20005799001f16ddcb99):
```
commit a4dfe7e6a2ec78ba9cea20005799001f16ddcb99 (origin/oesteban-patch-2)
Author: Oscar Esteban <code@oscaresteban.es>
Date:   Thu Dec 13 16:41:55 2018 -0800

    [FIX] Update pytest req'd version to 3.6
    
    Fixes #2826.

diff --git a/nipype/info.py b/nipype/info.py
index 1cf361c40..be6edb713 100644
--- a/nipype/info.py
+++ b/nipype/info.py
@@ -108,7 +108,7 @@ NUMPY_MIN_VERSION_37 = '1.15.3'
 SCIPY_MIN_VERSION = '0.14'
 TRAITS_MIN_VERSION = '4.6'
 DATEUTIL_MIN_VERSION = '2.2'
-PYTEST_MIN_VERSION = '3.0'
+PYTEST_MIN_VERSION = '3.6'
 FUTURE_MIN_VERSION = '0.16.0'
 SIMPLEJSON_MIN_VERSION = '3.8.0'
 PROV_VERSION = '1.5.2'
```
seems to run tests just fine on debian stretch with 3.0.6-1 .

**Comment by yarikoptic** [comment]
ah, @oesteban - please disregard my above questsion -- did not spot https://github.com/nipy/nipype/issues/2826  which somewhat explains the reason.  I think for the Debian package I would just eliminate any versioning of the dependency since it would install most recent available, and fail if fails to build/test

**Comment by effigies** [comment]
Okay. So we may wish to drop that requirement, but that means either setting a max version on xdist, which itself set a minimum version of 3.6 (see #2826, #2827) or dropping the requirement for xdist, which will in turn require removing the `-n auto` from the [`pytest.ini`](https://github.com/nipy/nipype/blob/master/nipype/pytest.ini). At which point, we'd want to instruct Travis and Circle to install `pytest-xdist` separately, and add `-n auto` for the sake of speed.

I'm fine with all of this. It's just a little rabbit hole.

**Comment by yarikoptic** [comment]
Thank you @effigies !  whatever you feel works ok for you is ok with me  -- at least I can workaround.

**Pull request merged**
