### PR TITLE
ENH nipype_display_crash defaults to last created pkl file

### PR DESCRIPTION
**Pull request by shoshber**

### CODE REVIEW

**Comment by shoshber** [comment]
ack, the travis build failed because of a network issue. How do I retry the build without pushing an empty commit?

**Comment by chrisfilo** [comment]
You have write access to the nipy/nipype repo so yo ushould be able to
restart jobs when you log into travis-ci.org

**Comment by satra** [comment]
@shoshber - do look at this PR #1608 before making too many changes here. 

we will want that PR merged before this one.

**Comment by satra** [comment]
@shoshber - now that the new `nipypecli` has been merged, this should focus on building on top of the command there (in scripts)

**Pull request closed without merging**
