### PR TITLE
MAINT: Refactoring the way nipype checks Node hashes

### PR DESCRIPTION
**Pull request by oesteban**
Hopefully, to make it a bit simpler. This could affect #2380.

Main ideas:
* [x] Add a new `Node.is_cached()` member, trying to remove the responsibility of checking hashes from teh Plugins and putting it all in the Node context.
* [x] Simplify `Node.hash_value()` with the use of `is_cached()`.
* [x] `Node.needed_outputs` is now a property (allowing some checks when setting).
* [x] Coordinate `get_inputs`, hash calculation, `needed_outputs` calculation and the hash elements: `_hashvalue` and `_hashed_inputs`

### CODE REVIEW

**Comment by oesteban** [comment]
Maybe not necessary for this release, if you guys are very busy (as I imagine), but this should simplify hashing nodes. It'd be great to hear from @satra on this.

**Comment by effigies** [comment]
I don't feel capable of reviewing this before 1.0. @mgxd @satra if you do, please tag it with the 1.0 milestone.

**Comment by satra** [comment]
@oesteban - this looks good to me.

**Comment by satra** [comment]
@effigies - your call if you want to include this in 1.0. it will make the code look a lot cleaner.

**Comment by satra** [comment]
@effigies - it would be fine with me to include this.

**Comment by effigies** [comment]
No objections from me, I just haven't reviewed it, myself. Feel free to merge.

**Pull request merged**
