### PR TITLE
ENH: Add Quickshear

### PR DESCRIPTION
**Pull request by effigies**
Adds [Quickshear](https://github.com/nipy/quickshear) defacing algorithm.

### CODE REVIEW

**Comment by effigies** [comment]
Docker failure happening here, too.

**Comment by satra** [comment]
auto test?

**Comment by effigies** [comment]
Gah. I really thought I was going to get this one in one commit.

**Comment by satra** [comment]
perhaps this will incentive to consider what role the auto tests play and how we can address that role otherwise. actually it's the make specs check for metadata that i am generally most interested in.

**Pull request merged**
