### PR TITLE
MAINT: Adjust test names to placate make specs

### PR DESCRIPTION
**Pull request by effigies**
This addresses case-sensitive idiosyncrasies between filesystems that caused several autotests to be wrongly generated on Linux (CompCor, ErrorMap, Overlap, TSNR) and deleted on OSX (PatchMatch, Registration).

Changes proposed in this pull request
- Capitalize lowercased non-auto-tests
- Add "extra" keyword to tests that sat alongside auto tests.

cc @mgxd @djarecka

### CODE REVIEW

**Comment by djarecka** [comment]
@effigies works great! `make specs` doesn't change anything on my OSX. Thanks!

**Comment by effigies** [comment]
Seems to be failing to build the Docker image because the AFNI server is down.

**Comment by djarecka** [comment]
@effigies AFNI works today, you can rebuild it now

**Comment by effigies** [comment]
On it.

**Pull request merged**
