### PR TITLE
ENH Allow input weight for AFNI's volreg.

### PR DESCRIPTION
**Pull request by williford**
This is a clean PR, based on the suggestions in https://github.com/nipy/nipype/pull/2155.

I'm having some issues with running `make check-before-commit`. I will look into it more soon.

### CODE REVIEW

**Comment by effigies** [comment]
If it helps, you can have a look at these changes: https://github.com/nipy/nipype/compare/master...effigies:afni_volreg_inweight

I was attempting to push to your branch yesterday. I haven't updated them to push onto this PR because I don't want to clog the Circle queue just now. Feel free to reset to that branch, or pull onto your old branch, or just use them to compare your changes.

**Comment by williford** [comment]
I just needed have the required dependencies to run the tests. Feel free to make whatever changes you think should be made - or merge your version.

**Comment by effigies** [comment]
I think this is good to go. Anybody up for a review?

**Comment by williford** [comment]
It looks good to me. Thanks a lot for your work @effigies!

**Pull request merged**
