### PR TITLE
[ENH] FSL maths interface, add the remaining dimension reduction operations…

### PR DESCRIPTION
**Pull request by imalone**
A number of the fslmaths -T dimension reduction operations were missing from the interface, this pull request adds support for them: MaxnImage (-Tmaxn), MinImage (-Tmin), MedianImage (-Tmedian), PercentileImage (-Tperc P), AR1Image (-Tar1) and the -X/-Y/-Z forms.

### CODE REVIEW

**Comment by imalone** [comment]
Thanks.
It wanted to also add or change the following files which I haven't committed as they don't relate to the interfaces I added:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   nipype/interfaces/afni/tests/test_auto_Autobox.py
	modified:   nipype/interfaces/utility/tests/test_auto_Merge.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	fsl.patch
	nipype/algorithms/tests/test_auto_CompCor.py
	nipype/algorithms/tests/test_auto_ErrorMap.py
	nipype/algorithms/tests/test_auto_Overlap.py
	nipype/algorithms/tests/test_auto_TSNR.py
	nipype/interfaces/ants/tests/test_auto_KellyKapowski.py
	nipype/interfaces/fsl/tests/test_auto_AccuracyTester.py
	nipype/interfaces/fsl/tests/test_auto_Classifier.py
	nipype/interfaces/fsl/tests/test_auto_Cleaner.py
	nipype/interfaces/fsl/tests/test_auto_FeatureExtractor.py
	nipype/interfaces/fsl/tests/test_auto_Training.py
	nipype/interfaces/fsl/tests/test_auto_TrainingSetCreator.py
```

**Comment by imalone** [comment]
I've merged with master on my fork (nipy/master branch actually, as my master is originally a fork of a different fork), but I can't see how I can update this pull request to come from that branch. Surely it's only the target branch that matters at this end anyway?

**Comment by satra** [comment]
@imalone - this is fine for now - it is the target branch that matters. however, we do like to sync up things from time to time.

**Comment by imalone** [comment]
Thanks, will try to remember in future, just a bit tricky in this instance.

**Pull request merged**
