### PR TITLE
[ENH] Mrtrix3 enhancements

### LINKED ISSUE #3400: MRConvert missing json-related keyword arguments' interfaces
### Summary
The MRConvert interface for mrtrix3's mrconvert function is missing the json-related keyword arguments (import and export).

### Actual behavior
Using these option currently requires the user to state them under "args". 

### Expected behavior
Would be great if there will be corresponding inputs under InputSpec.

### PR DESCRIPTION
**Pull request by GalBenZvi**
## Summary
Made some changes and additions to Mrtrix3's interfaces in the nipype platform.

Fixes #3400 and #3402 .

## List of changes proposed in this PR (pull-request)

- Added json and gradient table-related  kwargs to *mrconvert* interface.
- Added *mrcat*interface.
- Added *mrtransform* interface.

## Acknowledgment

- [] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by ZviBaratz** [comment]
Hi :smiley:

@GalBenZvi and I are trying to get this PR to pass the build (the tests pass locally), but it seems like we're missing something.

There are two issues we're currently facing:
1. Contribution checks' tests raising:
```
 M nipype/interfaces/mrtrix3/tests/test_auto_BrainMask.py
 M nipype/interfaces/mrtrix3/tests/test_auto_ConstrainedSphericalDeconvolution.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIBiasCorrect.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIDenoise.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIExtract.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIPreproc.py
 M nipype/interfaces/mrtrix3/tests/test_auto_EstimateFOD.py
 M nipype/interfaces/mrtrix3/tests/test_auto_FitTensor.py
 M nipype/interfaces/mrtrix3/tests/test_auto_Generate5tt.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRCat.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRConvert.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRDeGibbs.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRMath.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRResize.py
 M nipype/interfaces/mrtrix3/tests/test_auto_ResponseSD.py
 M nipype/interfaces/mrtrix3/tests/test_auto_TensorMetrics.py
 M nipype/interfaces/mrtrix3/tests/test_auto_Tractography.py
++ git status -s
+ test -z ' M nipype/interfaces/mrtrix3/tests/test_auto_BrainMask.py
 M nipype/interfaces/mrtrix3/tests/test_auto_ConstrainedSphericalDeconvolution.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIBiasCorrect.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIDenoise.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIExtract.py
 M nipype/interfaces/mrtrix3/tests/test_auto_DWIPreproc.py
 M nipype/interfaces/mrtrix3/tests/test_auto_EstimateFOD.py
 M nipype/interfaces/mrtrix3/tests/test_auto_FitTensor.py
 M nipype/interfaces/mrtrix3/tests/test_auto_Generate5tt.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRCat.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRConvert.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRDeGibbs.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRMath.py
 M nipype/interfaces/mrtrix3/tests/test_auto_MRResize.py
 M nipype/interfaces/mrtrix3/tests/test_auto_ResponseSD.py
 M nipype/interfaces/mrtrix3/tests/test_auto_TensorMetrics.py
 M nipype/interfaces/mrtrix3/tests/test_auto_Tractography.py'
Error: Process completed with exit code 1.
```
2. Even though the pre-commit hook is run successfully before pushing, it seems like there are many formatting changes being applied. 

@effigies @satra I tried looking into [`checkspecs.py`](https://github.com/nipy/nipype/blob/3782d28e846c34bb97749c3724933b3a76f7ad06/tools/checkspecs.py) but haven't managed to track down the problem. Any help resolving this would be greatly appreciated :pray:

**Comment by effigies** [comment]
Hi @ZviBaratz @GalBenZvi, apologies for the very slow response. I went ahead and pared down a lot of the unrelated changes and squashed this into a single commit in #3445. Could you review that and let me know if that fully replaces what you were trying to do here?

**Comment by GalBenZvi** [comment]
Hi @effigies,
The PR looks good (I think it's most of what I tried to add some time ago but had some trouble with the checks).

I was wondering whether you'd like me to create interfaces to some other *mrtrix*'s functions?
I saw there's another release coming and wouldn't want to delay it.

**Comment by effigies** [comment]
@GalBenZvi Thanks for looking it over. I'm going to try to release tomorrow or the day after, but please feel free to submit more interfaces when you have the opportunity.

**Pull request closed without merging**
