### PR TITLE
REL: 1.8.7

### PR DESCRIPTION
**Pull request by effigies**
Preparation for the 1.8.7 release. It's just been a while and we have over 184 commits since the last release. This is not urgent.

The following users have made their first contributions:

* @asmacdo made their first contribution in https://github.com/nipy/nipype/pull/3561
* @yibeichan made their first contribution in https://github.com/nipy/nipype/pull/3568
* @mmbannert made their first contribution in https://github.com/nipy/nipype/pull/3558
* @mauriliogenovese made their first contribution in https://github.com/nipy/nipype/pull/3556
* @l-espana made their first contribution in https://github.com/nipy/nipype/pull/3529
* @jadecci made their first contribution in https://github.com/nipy/nipype/pull/3583
* @manuegrx made their first contribution in https://github.com/nipy/nipype/pull/3577
* @pvelasco made their first contribution in https://github.com/nipy/nipype/pull/3554
* @dependabot made their first contribution in https://github.com/nipy/nipype/pull/3598
* @stebo85 made their first contribution in https://github.com/nipy/nipype/pull/3629
* @zachlindsey made their first contribution in https://github.com/nipy/nipype/pull/3637
* @teanijarv made their first contribution in https://github.com/nipy/nipype/pull/3630
* @lbutry made their first contribution in https://github.com/nipy/nipype/pull/3613

Please let me know if you would like to be credited in releases, and if so what name, ORCID and affiliation you would like. See https://github.com/nipy/nipype/blob/master/.zenodo.json for examples. If you have already added yourself, no need to respond.

Quick issues/PRs:

* ... Please let me know if you want to try to merge something in before the release.

## Release checklist

* [ ] Merge pending PRs
* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py`
* [x] Update `doc/interfaces.rst` with previous releases

### CODE REVIEW

**Comment by yibeichan** [comment]
thank you! but my PR was a very minor one...next time when I make more contributions I'll add myself

**Comment by effigies** [comment]
@djarecka Can you create a new `TUTORIAL_ACCESS_TOKEN`? I believe it's a PAT on https://github.com/miykael/nipype_tutorial. I do not have permissions there.

**Comment by djarecka** [comment]
> @djarecka Can you create a new `TUTORIAL_ACCESS_TOKEN`? I believe it's a PAT on https://github.com/miykael/nipype_tutorial. I do not have permissions there.

`TUTORIAL_ACCESS_TOKEN` is nipype secret, I don't have admin access on nipype tutorial, but can try to update out secret with my PAT

**Comment by effigies** [comment]
Looks like something went wrong: https://github.com/miykael/nipype_tutorial/actions/runs/8376744890

**Comment by djarecka** [comment]
> Token seems to work, but it looks like something went wrong with the action itself: https://github.com/miykael/nipype_tutorial/actions/runs/8376744890

yes, looks like there is problem with building

**Comment by effigies** [comment]
@mgxd I think you last fixed things related to DLC in https://github.com/miykael/nipype_tutorial/pull/182. Any ideas?

**Comment by djarecka** [comment]
slightly more info here: https://github.com/miykael/nipype_tutorial/actions/runs/8377012805/job/22938063788

Can also take a look later today

**Comment by mgxd** [comment]
Looks like the DLC action we were using has been orphaned - there's a maintained fork here https://github.com/jpribyl/action-docker-layer-caching

**Pull request closed without merging**
