### PR TITLE
REL: 1.1.1

### PR DESCRIPTION
**Pull request by effigies**
Waiting on:

* [x] #2637

### CODE REVIEW

**Comment by effigies** [comment]
@mgxd Should be ready for things like zenodo and mailmap updates.

**Comment by djarecka** [comment]
@effigies - running the tests, will let you know

**Comment by djarecka** [comment]
@effigies - looks like niype_tutorial is [fine](https://github.com/djarecka/nipype_tutorial/pull/16)

Also, I've just noticed that `xdist` have already a new release `1.22.5` :)  I don't remember which exactly travis job was giving you error on Friday, but it looks like `travis_retry` is not needed anymore.
https://github.com/djarecka/nipype/pull/5

**Comment by effigies** [comment]
Sounds good. Since it's not anything that will end up in the distribution, we can fix that after release. Merging.

**Pull request merged**
