### PR TITLE
REL: 1.5.0

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Accidentally closed #3174 by trying to keep master synced with 1.5.0-rc1.post-dev.

Prep for new feature release 1.5.0, targeting release when we can manage it.

Require merge or postponement decision on all issues/PRs in https://github.com/nipy/nipype/milestone/38:

* [ ] FIX Ants N4BiasFieldCorrection rescale_intensities bug #3139 (@salma1601)

Will try review the open PRs and see if anything is close enough to push on, tomorrow.

## Release checklist

* [ ] Merge pending PRs
* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py`
* [x] Update `doc/interfaces.rst` with previous releases
* [ ] Check conda-forge feedstock build (conda-forge/nipype-feedstock#67)
* [ ] Tutorial tests (https://circleci.com/workflow-run/be312bea-8273-47cf-9e52-54257d969422)

## Uncredited authors

The following authors have contributed, but not added themselves to the [`.zenodo.json`](https://github.com/nipy/nipype/blob/master/.zenodo.json) file. If you would like to be an author on Zenodo releases, please add yourself or comment with your preferred publication name, affiliation and [ORCID](https://orcid.org/). If you would like to stop being spammed whenever I'm the one doing releases, let me know, and I'll add you to a blacklist.

No entry to sort: cdla (@cdla)
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Victor Férat (@vferat)
No entry to sort: Niklas Förster (@niklasfoe)
No entry to sort: Kirstie Whitaker (@KirstieJane)
No entry to sort: Pablo Polosecki (@polosecki)
No entry to sort: Ami Tsuchida
No entry to sort: Daniel Brenner (@brennerd11)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Kevin Sitek (@sitek)
No entry to sort: Luke Bloy (@bloyl)
No entry to sort: Martin Luessi (@mluessi)
No entry to sort: steve (@steve19922)
No entry to sort: Charl Linssen (@turingbirds)
No entry to sort: Félix C. Morency (@fmorency)
No entry to sort: Michiel Cottaar (@MichielCottaar)
No entry to sort: Regina Kim (@reginakim)
No entry to sort: Valentin Haenel (@esc)
No entry to sort: Xu Wang
No entry to sort: maedoc (@maedoc)

I am unable to find GitHub handles for Ami Tsuchida or Xu Wang.

Apologies also to anybody who may have added themselves previously and been removed by the automated reordering. I think that's fixed these days.

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
@satra Because reverting to older nipype that was known to pass the tutorials still fails the CI tests, I wonder if we shouldn't go ahead and release 1.5.0 (merging in master and updating changelog/contributors, of course).

I know @djarecka is debugging the tutorials again, but I would suggest setting a reasonable time limit to see if she can make it happen and otherwise going on with the release.

**Comment by satra** [comment]
@effigies - seems like a reasonable plan.

**Comment by effigies** [comment]
@sulantha2006, @jhuguetn, @ZviBaratz, @daniel-ge I would like to add you to the authors list on the Zenodo file. Is that okay, and what name, affiliation and ORCID would you like added?

**Comment by sulantha2006** [comment]
Hi Chris,
Thank you and it's completely fine.

Use the following info.
sulantha.s@gmail.com
Enigma Biomedical Group

Thank you very much.

**Comment by ZviBaratz** [comment]
Gladly.

Zvi Baratz
Sagol School of Neuroscience, Tel Aviv University

Thank you!

**Comment by jhuguetn** [comment]
Sure, thanks @effigies  

Jordi Huguet
BarcelonaBeta Brain Research Center
orcid.org/0000-0001-8420-4833

**Comment by daniel-ge** [comment]
Hi Chris, yes, that would be great. Please use the following:

Daniel Geisler

Division of Psychological and Social Medicine and Developmental Neuroscience, Faculty of Medicine, Technische Universität Dresden, Dresden, Germany

https://orcid.org/0000-0003-2076-5329

Thank you,
Daniel

**Pull request merged**
