### PR TITLE
CI: Test 3.7, resume testing nipy extras

### PR DESCRIPTION
**Pull request by effigies**
## List of changes proposed in this PR (pull-request)

* Add Python 3.7-dev to test matrix
* Remove "fmri" extra removed in 3500213074f28def0f011ff59a1519fb2fd377b4

@satra Should `fmri` instead be replaced with `nipy` in Travis?

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by djarecka** [comment]
@effigies - if you want you can also test py 3.7 from xenial, https://github.com/travis-ci/travis-ci/issues/9815

**Comment by djarecka** [comment]
@effigies - this is the [syntax I used in pynidm](https://github.com/incf-nidash/PyNIDM/blob/master/.travis.yml). Probably can be done bettrer, but it works. Hopefully, this is only temporary, so either xenial or 3.7-dev works fine.

**Comment by effigies** [comment]
That seems to only grab one entry from the env matrix...

**Comment by effigies** [comment]
So it looks like only Xenial has 3.7, and only Trusty has 3.4. So not sure there's going to be a nice Travis matrix solution to get both without double-enumerating the environment.

**Comment by effigies** [comment]
I think it probably makes the most sense to move to Xenial, and duplicate the matrix for 3.4, as that's going to be end-of-life soonest.

**Comment by effigies** [comment]
Okay, this is set. @satra We haven't been testing interfaces that require `nipy` extras on Travis, so I haven't re-added it, but let me know if you think we should.

**Comment by effigies** [comment]
(I just cancelled the Circle tests, since this is just futzing with Travis.)

**Comment by effigies** [comment]
I'm interpreting that as `INSTALL_DEB_DEPENDENCIES=true`.

**Comment by satra** [comment]
i think it's reasonable to ask, i don't know how much work it would be for them. @arokem - is there a practical obstacle to dipy wheels for 3.7 (now that it is available)?

**Pull request merged**
