### PR TITLE
[MRG] fix: update provenance creation to use released prov library

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by satra** [comment]
@chrisfilo, @bcipolli  - this is ready for review

**Comment by bcipolli** [comment]
@satra is it possible to create a separate pull request for @effigies nibabel deprecation changes? It makes the code review much more challenging to mix the two together.

**Comment by effigies** [comment]
Would a rebase resolve it? Because that commit should already be in master.

**Comment by satra** [comment]
this should be better, but i was also a little sloppy with the commits and committed a few other things!

**Comment by bcipolli** [comment]
It's OK--this is *way better*, much easier to review. Thanks!

**Comment by satra** [comment]
hey folks, any thoughts here. i'd like to merge this as it ensures we have a clean install and operation across systems.

**Comment by bcipolli** [comment]
Sorry @satra , I don't know the first thing about provenance, nor this package. Downloaded some things to read, but won't be able to get to them until Friday or so..

**Pull request merged**
