### PR TITLE
rel: 1.0.3

### PR DESCRIPTION
**Pull request by mgxd**

### CODE REVIEW

**Comment by effigies** [comment]
@mgxd I merged master in. @djarecka Could you start the tutorial tests?

**Comment by effigies** [comment]
@yarikoptic Can you check for any Debian packaging issues? The only remaining changes should be minor documentation updates.

**Comment by effigies** [comment]
Feedstock [passing](https://github.com/conda-forge/nipype-feedstock/pull/14).

**Comment by djarecka** [comment]
nipype tutorial tests are [passing](https://circleci.com/gh/djarecka/nipype_tutorial/101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by effigies** [comment]
Can you add a changelog entry for #2559?

**Pull request merged**
