### PR TITLE
 FIX: Update logging levels in enable_debug_mode 

### LINKED ISSUE #1169: config.enable_debug_mode() does not work as advertised
config.enable_debug_mode() is not equivalent to:

```
mkdir ~/.nipype
echo "[logging]" > ~/.nipype/nipype.cfg
echo "workflow_level = DEBUG" ~/.nipype/nipype.cfg
echo "interface_level = DEBUG" >> ~/.nipype/nipype.cfg
echo "filemanip_level = DEBUG" >> ~/.nipype/nipype.cfg
```

### PR DESCRIPTION
**Pull request by effigies**
Fixes #1169

Changes proposed in this pull request
- Update logging levels in enable_debug_mode 
- Add a test

### CODE REVIEW

**Comment by satra** [comment]
i don't think this was really a bug. if we treat it as such (and i am fine with the change) we should update this as well:

http://nipype.readthedocs.io/en/latest/users/config_file.html#debug-configuration

**Comment by effigies** [comment]
It does seem weird to `enable_debug_mode` and only change the config without changing the log levels the config refers to.

That said, if `utils_level` wasn't intended to be part of it, I'm okay with removing that. That may be too noisy. Will update the docs.

**Comment by satra** [comment]
also this docs: http://nipype.readthedocs.io/en/latest/users/debug.html

so we did have proper instructions for debug mode.

i would use this opportunity to clean up and make debug mode as useful as possible. so go ahead with your changes.

**Comment by effigies** [comment]
Any further comments? Hoping to merge these last four PRs in batch when @mgxd's tests pass.

**Comment by satra** [comment]
lgtm

**Pull request merged**
