### PR TITLE
fix: support for stricter checking with ants bsplinesyn

### PR DESCRIPTION
**Pull request by satra**
@hjmjohnson - does this seem reasonable?

### CODE REVIEW

**Comment by roelant001** [comment]
Dear @satra and @ntustison 

I'm still encountering this issue. I've installed the most recent version from github. Am I doing something wrong or is this "bug" still persisting? When manually removing the .0's from the command and running it, it runs successfully. Any suggestions?


relevant settings: 
```
reg.inputs.transforms = ['Translation','Rigid', 'Affine', 'SyN', 'BSplineSyN']
reg.inputs.transform_parameters = [(0.1,),(0.1,), (0.1,), (0.2, 3.0, 0.0),(0.25,25,0)]

Description: itk::ERROR: CommandLineParser(0x183c7b0): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert '25.0' to type 'j' as unsigned int
```

**Comment by ntustison** [comment]
I accommodated this issue on the ANTs side with this commit

https://github.com/stnava/ANTs/commit/05ed1bad5605ddba7a2f0a7faeaf6919e5af66a3

**Comment by satra** [comment]
@roelant001 - BSplineSyn needs 4 parameters, not 3, so the three parameter version is being cast to all floats.

see: https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/registration.py#L316

**Comment by roelant001** [comment]
Thanks!! @ntustison and @satra for this (very simple) explanation and solution.
I assumed the 4th parameter (splineOrder) would default when left empty. Assumptions...

**Pull request merged**
