### PR TITLE
FIX: Can't seem to import workflows from niflows in CircleCI

### PR DESCRIPTION
**Pull request by oesteban**
Master is broken -- this PR relocates the pip install of
``niflow-nipype1-workflows`` so that it happens AFTER nipype
was installed.

## Summary

Fixes # .

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by oesteban** [comment]
Blocked by niflows/nipype1-workflows#5

**Comment by satra** [comment]
@oesteban - merged do we need to make a new release there first? 

i don't know if @effigies did the release manually or through travis or some combination. i do see twine is being installed.

**Comment by oesteban** [comment]
It seems manual: https://github.com/niflows/nipype1-workflows/blob/master/.travis.yml

**Comment by effigies** [comment]
Oh, yeah, it's manual. Give me a minute to release.

**Comment by effigies** [comment]
Pushed to PyPI.

**Comment by oesteban** [comment]
Thx!

**Pull request merged**
