### PR TITLE
more robust access to neurodebian

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by oesteban** [comment]
There's a problematic point in that script: one apt-get install without the -y option (or similar, I don't recall exactly). It rarely fails, but sometimes it does. I wrote a fix: https://gist.github.com/oesteban/a0d8972f978339910bf4

**Comment by satra** [comment]
@yarikoptic - hey yarik one change requested to neurodebian install script :)

**Comment by satra** [comment]
@oesteban - you can submit a pull request to neurodebian

**Comment by chrisfilo** [comment]
Yup - it's here:
https://github.com/neurodebian/neurodebian/blob/master/tools/neurodebian-travis.sh

**Pull request merged**
