### PR TITLE
GIFT Nipype Interface

### PR DESCRIPTION
**Pull request by calhounlab**
## Summary

Fixes # .

## Acknowledgment

- [ ] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by calhounlab** [comment]
[nipype.zip](https://github.com/nipy/nipype/files/2980432/nipype.zip)

**Comment by mgxd** [comment]
hi @calhounlab - can you include a summary of the changes you are making and why they are needed? Thanks!

**Comment by calhounlab** [comment]
Hi Mathias,

Thanks for replying back to me. We want to add GIFT interface in list of
nipype interfaces similar to fsl, spm. Basically we didn't change any of
the nipype original files. If you put the gift package under
nipype/interfaces it should work fine.

Thanks,
Sri

**Comment by mgxd** [comment]
Ok - I did see new additions in the .zip file you included. The changes here have already been merged, but it would be nice to add GIFT support natively to nipype. Could you open a new PR adding the changed files in your .zip?

**Comment by effigies** [comment]
This PR is from `nipy:master` into `nipy:dev/2.0`. Sorry to be a little abrupt, but I want to close this to prevent accidental damage to the `dev/2.0` branch. @calhounlab Do you need help forking, and creating a new pull request?

**Comment by calhounlab** [comment]
Thanks Mathias and Chris

**Comment by calhounlab** [comment]
I think its almost same version we have if you already integrated in the
nipype development version. Will be adding some features and get back to
you may be next month.

**Pull request closed without merging**
