### PR TITLE
New interface for fslcpgeom (with the output of check-before-commits...)

### PR DESCRIPTION
**Pull request by mick-d**
I was not sure of the best way to implement `fslcpgeom` to make sure that the file provided are not modified (contrarily to fsl behaviour). It would be great to have some feedback on this.

Note: the new interface is `CopyGeom` in `interfaces/fsl/utils.py`

### CODE REVIEW

**Comment by satra** [comment]
@mick-d - there appears to be a lot of unrelated changes. could you please merge with current master, run `make check-before-commit` and then push. i'm a little surprised a the number of other changes.

**Comment by mick-d** [comment]
@satra I did all that. I think the reason for all the other changes is that quite a few PRs have been submitted without running check-before-commit (if you look at the changes in other files, most of them are formatting corrected by check-before-commit)

**Comment by mick-d** [comment]
(and test files, all created by check-before-commit)

**Comment by satra** [comment]
@mick-d - i fixed some of that yesterday. could you try merging now?

**Comment by mick-d** [comment]
Sure!

**Pull request closed without merging**
