### PR TITLE
ENH: REF: SSHDataGrabber should grab related file

### PR DESCRIPTION
**Pull request by ashgillman**
SSHDataGrabber will optionally download files, however if requested file is a header file, the corresponding data file won't be downloaded. This PR fixes this issue.

## Changes
- Refactored current file downloading, which was replicated in two areas, to one function
- Added test for SSHDataGrabber, demonstrating the issue and its correction
- When downloading files, and files with a related file type in the same directory are also downloaded

### CODE REVIEW

**Comment by ashgillman** [comment]
The CircleCI failure looks to be unrelated: an issue w/ dependency resolution for FSL and AFNI

**Comment by jdkent** [comment]
Looks like the same/similar issue we had here: poldracklab/fmriprep#566, probably need to update the docker file in a separate pull request.

**Comment by effigies** [comment]
This was fixed in #2075. Just merge or rebase on master.

**Comment by ashgillman** [comment]
Ah thanks, I thought the CI would have run against what the code would be after a merge, not the pre-merge. I have rebased

**Comment by ashgillman** [comment]
I'm actually surprised the SSH tests ran already... The CI must be able to SSH back to itself by default.

But I went through the logs and this line exists:

    ../src/nipype/nipype/interfaces/io.py::nipype.interfaces.io.SSHDataGrabber PASSED

And I confirmed that the test fails locally without the final commit locally.

**Comment by ashgillman** [comment]
Uh oh, my bad:

    ../src/nipype/nipype/interfaces/tests/test_io.py::test_SSHDataGrabber SKIPPED

I guess I need to add paramiko to the CI dependencies.

**Comment by ashgillman** [comment]
So it looks like SSHing to localhost on CI might be a little tricky, I thought it would be a simple way to add tests of the functionality.

What do others think of leaving the test, but marking it not to be checked my CI. The functionality is currently not tested at all, at least this way it can be manually tested.

**Comment by effigies** [comment]
Sorry I completely dropped the ball on this. If I'm understanding the issue, it looks like there's no SSH server? If so, I guess there are three options:

1) Skip the test, and make sure it works on your own machine.
2) Install openssh-server in the nipype containers, so you can login to localhost.
3) Spin up an SSH server with parmiko (a quick look at the docs suggests this is possible, but I have no familiarity with the library and may have misinterpreted)

In any event, you'll need to merge master and resolve conflicts to resume this PR. Apologies again.

**Comment by ashgillman** [comment]
Hey. Thanks for responding, I was actually just looking for this yesterray, I have been reading a few changes. I think 2 would be a good solution. If I rebase, are you able to help with the container side?

**Comment by effigies** [comment]
Sure.

**Comment by ashgillman** [comment]
Okay, rebase and test_io.py running successfully locally

**Comment by effigies** [comment]
Great, thanks. I spent some time last night playing with installing and running `openssh-server` on nipype Docker images. It's somewhat complicated by the fact that there doesn't seem to be a good way to run a daemon in a container directly. It can be done, but I'm not sure that it's a good approach, since it'll need to be scripted from outside Docker.

I'm going to have a look at creating servers with paramiko. If we can simulate a server from within the tests, I think that would be ideal.

In the short term, I think it would be useful to have another pytest skip criterion that checks whether there is an SSH server running on localhost (with a port parameter that defaults to 22). Given that we need paramiko installed anyway, perhaps there is functionality there that will make it easy.

**Comment by ashgillman** [comment]
Good temp fix.

Python2:

```
[nix-shell:~/dev/nipy@github.com/nipype]$ sudo systemctl start ssh                                                                       
                                                                                                                                         
[nix-shell:~/dev/nipy@github.com/nipype]$ pytest nipype/interfaces/tests/test_io.py                                                      
========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.14, pytest-3.2.5, py-1.4.34, pluggy-0.4.0                                                                  
rootdir: /home/gil2a4/dev/nipy@github.com/nipype/nipype, inifile: pytest.ini                                                             
collected 28 items                                                                                                                        
                                                                                                                                         
nipype/interfaces/tests/test_io.py .s......s..ss...........sss.                                                                          
                                                                                                                                         
================================================== 21 passed, 7 skipped in 0.92 seconds ==================================================
                                                                                                                                         
[nix-shell:~/dev/nipy@github.com/nipype]$ sudo systemctl stop ssh                                                                        
                                                                                                                                         
[nix-shell:~/dev/nipy@github.com/nipype]$ pytest nipype/interfaces/tests/test_io.py                                                      
========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.14, pytest-3.2.5, py-1.4.34, pluggy-0.4.0
rootdir: /home/gil2a4/dev/nipy@github.com/nipype/nipype, inifile: pytest.ini                                                             
collected 28 items                                                                                                                        
                                                                                                                                         
nipype/interfaces/tests/test_io.py .s......s..ss...........ssss                                                                          
                                                                                                                                         
================================================== 20 passed, 8 skipped in 0.12 seconds ==================================================
```
And Python 3
```
[nix-shell:~/dev/nipy@github.com/nipype]$ sudo systemctl start ssh                                                                        
[sudo] password for gil2a4:                                                                                                                                                                                                                                                         
[nix-shell:~/dev/nipy@github.com/nipype]$ pytest nipype/interfaces/tests/test_io.py                                                       ========================================================== test session starts ===========================================================
platform linux -- Python 3.6.4, pytest-3.2.5, py-1.4.34, pluggy-0.4.0                                                                     rootdir: /home/gil2a4/dev/nipy@github.com/nipype/nipype, inifile: pytest.ini                                                              
collected 28 items                                                                                                                                                                                                                                                                  
nipype/interfaces/tests/test_io.py .s......s..ss...........sss.                                                                                                                                                                                                                     
================================================== 21 passed, 7 skipped in 0.78 seconds ==================================================
                                                                                                                                          
[nix-shell:~/dev/nipy@github.com/nipype]$ sudo systemctl stop ssh                                                                         
                                                                                                                                          
[nix-shell:~/dev/nipy@github.com/nipype]$ pytest nipype/interfaces/tests/test_io.py                                                       
========================================================== test session starts ===========================================================
platform linux -- Python 3.6.4, pytest-3.2.5, py-1.4.34, pluggy-0.4.0                                                                     
rootdir: /home/gil2a4/dev/nipy@github.com/nipype/nipype, inifile: pytest.ini                                                              
collected 28 items                                                                                                                        
                                                                                                                                          
nipype/interfaces/tests/test_io.py .s......s..ss...........ssss                                                                           
                                                                                                                                         
================================================== 20 passed, 8 skipped in 0.14 seconds ==================================================
```

**Comment by effigies** [comment]
Hey, thanks for poking at this some more. Just as an update, I've taken a couple shots at creating an SSH server with paramiko and have failed pretty hard. I'm a little inclined to verify your tests work locally, skip properly on circle, and add an issue to hack together an SSH server in a separate PR.

**Comment by effigies** [comment]
Okay, I can verify tests pass locally, and turning my SSH server off and on toggles the number of skipped tests. Pushing a fix for the Dockerfile (we now edit a Dockerfile-generating script), and I think this should be good to go, as far as I'm concerned.

**Comment by ashgillman** [comment]
Not sure about that 1 Travis error... Some sort of time out? Can you ask it to run that test again?

**Comment by effigies** [comment]
Looks like a Python 2 issue.

**Comment by effigies** [comment]
The CircleCI build had a `Cannot assign requested address` socket error, which suggests that possibly `localhost` isn't bound to an address, so I switched to using `127.0.0.1`. And the Travis error was a timeout, so I added a 10s timeout to the SSH connect statements. Let's see if those work.

**Comment by ashgillman** [comment]
Strange that you'd only get such errors with Python 2, but glad the tests ran. Thank for adding the last bit of work, I ran out of time on Friday afternoon :)

**Pull request merged**
