### PR TITLE
WIP: New Freesurfer, FSL, Dipy wrappers. Interfaces for Gmsh and GetDP

### PR DESCRIPTION
**Pull request by swederik**
This is a bit of a mixed of a pull request of stuff required for EEG forward modelling. See https://cyclotronresearchcentre.github.io/forward/

I would say it needs some more cleanup and testing before its ready to merge, though.

There are new wrappers for:

**Freesurfer**
- Transform2Talairach (mris_transform)
- FloodfillSurface (mris_fill)

**FSL**
- BETSurface (betsurf)
- DecomposeTensor (fslmaths -tensor_decomp)

**Dipy**
EstimateConductivity: scales diffusion tensor eigenvalues to estimate conductivity tensor, saves 6 volume file as Nifti

**Gmsh**
[Gmsh](http://geuz.org/gmsh/) is a 3D finite element grid generator with a build-in CAD engine and post-processor. Its design goal is to provide a fast, light and user-friendly meshing tool with parametric input and advanced visualization capabilities.

**GetDP** 
[GetDP](http://geuz.org/getdp/) is a general finite element solver using mixed elements to discretize de Rham-type complexes in one, two and three dimensions. The main feature of GetDP is the closeness between the input data defining discrete problems (written by the user in ASCII data files) and the symbolic mathematical expressions of these problems.

### CODE REVIEW

**Comment by djarecka** [comment]
@swederik - it looks like a big PR, are you considering merging with master and finishing?

**Comment by djarecka** [comment]
@swederik it looks like a big PR. Would you consider merging with master and finishing?

**Comment by swederik** [comment]
Oh wow... I actually haven't looked at this in years. It was stupid of me to put so many things into such a large PR. I have no idea if anyone would find these interfaces useful, or if they would just be extra stuff to maintain in Nipype. The Freesurfer / FSL interfaces might be useful to others. I guess the Dipy conductivity thing and getdp / gmsh are a bit too specific to bother putting into master. I really don't have time to deal with this at the moment, so I would lean towards closing unless someone wants to put the effort into it.

**Comment by djarecka** [comment]
@swederik - thanks for your answer!

@satra - do you have any suggestions? should we include any of these interfaces? do you have anyone to ping, who can be interested in using and reviewing them?

**Comment by oesteban** [comment]
I'll try to have a look

**Comment by effigies** [comment]
@oesteban I know you self assigned, but it seems unlikely you'll have much time for this. Feel free to reopen if I'm wrong.

**Pull request closed without merging**
