### PR TITLE
doc: fix rst formatting

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by effigies** [comment]
I take it this is meant to resolve the issue that's causing a ll Circle builds to fail?

**Comment by satra** [comment]
@effigies - yes. so we should merge this once tests pass.

however, i snuck in one change. `requires` no longer raises warnings.

**Comment by effigies** [comment]
Cancelled the previous build to move this one up in the queue (and because that one was going to fail anyway). If you want to merge master/rebase now, then we'll get test results on the latest merges, too.

**Comment by satra** [comment]
current master is merged in here.

**Comment by effigies** [comment]
So it is.

**Pull request merged**
