### PR TITLE
bug for datagrabber

### PR DESCRIPTION
**Pull request by anbai106**
There are two other classes in the io.py file, they maybe have the same problem, if you think my change works, you can also change the other two classes.

### CODE REVIEW

**Comment by satra** [comment]
@mgxd - could you please review this and make sure it functions as intended in the description for raise_on_empty?

**Comment by mgxd** [comment]
@anbai106 maybe we can add a new input field `drop_blank_outputs` that performs this check on top of `raise_on_empty`.

**Comment by mgxd** [comment]
@anbai106 the behavior you want would require a new input for datagrabber - something along the lines of 

```python
...
        if self.inputs.drop_blank_outputs:
            outputs[key] = [x for x in outputs[key] if x is not None]
        else:
            if any([val is None for val in outputs[key]]):
                outputs[key] = []
...
```

this behavior will potentially return lists of different sizes, which is dangerous when working with mapnodes / iterables across runs - thus, better to make a new input rather than build off of `raise_on_empty` 

(linking to related issue #1783)

This is very close to merge!

**Comment by effigies** [comment]
Hi @anbai106, are you going to have time to finish this up, soon?

**Comment by anbai106** [comment]
@effigies sorry for the delay, not so familiar with git pull request, i hope now everything is OK.

**Comment by mgxd** [comment]
@anbai106 we're just missing two things:

could add a new input for `DataGrabber` here?
https://github.com/nipy/nipype/blob/166e06cf5e8ec76cbbb16642f6526f093c28bfe5/nipype/interfaces/io.py#L1039
and make the changes from the [earlier comment](https://github.com/nipy/nipype/pull/1915#issuecomment-356078102)?

If you don't find time, we could make the changes for you, if that would be easier. Thanks!

**Comment by anbai106** [comment]
@mgxd , I am doing it now, if I make it wrong this time, you will be in charge of it, haha

**Comment by anbai106** [comment]
@mgxd I corrected like you proposed and merge my branch into the master branch, can you check if everything is ok?

**Comment by mgxd** [comment]
@anbai106 you'll have to `git push` your branch for us to see the changes

**Comment by effigies** [comment]
Hi @anbai106, I think you merged into your own master branch, which isn't going to show up here. Try the following:

```Shell
git remote add upstream git@github.com:nipy/nipype.git
git fetch upstream
```

This will make the official master branch available to you as `upstream/master`. Then we need to merge your current changes into the `anbai` branch, which is connected to this pull request.

```Shell
git checkout anbai
git merge master
```

Finally, I would recommend merging the current master, just to update the tests, then push:

```Shell
git merge upstream/master
git push
```

**Comment by anbai106** [comment]
@effigies finally, I think it is done :)
Thanks for your help

**Comment by effigies** [comment]
@anbai106 For some reason that latest version had some commit issues in it. I rebased your PR against the current master to remove the noise. Can you please check the [diff](https://github.com/nipy/nipype/pull/1915/files) and verify that it looks the way you intended?

**Comment by effigies** [comment]
@mgxd I think this is ready, unless you need tests.

**Pull request merged**
