### PR TITLE
MAINT: Revision of Zenodo update script

### PR DESCRIPTION
**Pull request by oesteban**
Unlocks the first position as per private conversation with @chrisgorgo.

### CODE REVIEW

**Comment by oesteban** [comment]
This should do :)

**Comment by oesteban** [comment]
Canceling CircleCI not to overload it

**Comment by effigies** [comment]
@oesteban Do you want to target the `rel/1.2.3` branch and run the updated script to reorder? That would be a good demonstration that it works.

**Comment by effigies** [comment]
Included in #3038.

**Pull request closed without merging**
