### PR TITLE
RF: Rearranging matmul order and using hermitian flag in ICC_rep_anova

### PR DESCRIPTION
**Pull request by kristoferm94**
## Summary
See https://github.com/nipy/nipype/issues/3450

## List of changes proposed in this PR (pull-request)
Calculation of predicted_Y refactored such that:
* numpy.dot is replaced with the @ operator 
* The pseudo-inverse of X.T@X is now calculated with the hermitian flag set to True (pinv uses a more efficient algorithm when the matrix input is assumed to be hermitian, which will always be the case with X.T@X in this function).
* The matrix multiplication order is changed in a way that we don't end up multiplying as many fat matrices as before.

### CODE REVIEW

**Review by effigies — APPROVED** [review]
Nice! I ran some quick tests just to see what this looks like. The reordering seems to dominate, but both changes seem well worth making.

**Comment by effigies** [comment]
I think you are going to want to remove the `dot` import from the top of the file, since it's no longer used. Otherwise looks good to me.

**Comment by kristoferm94** [comment]
I removed the numpy.dot import

**Comment by effigies** [comment]
Thanks!

**Pull request merged**
