### PR TITLE
skip python2 multiproc tests until the deadlock issue will be resolved

### PR DESCRIPTION
**Pull request by chrisfilo**
Temporary measure until: https://github.com/nipy/nipype/issues/1692 is resolved

### CODE REVIEW

**Comment by satra** [comment]
@chrisfilo - i'm worried that this doesn't solve the fundamental problem when people use multiproc. i'm going to take a look at the multiproc pieces, and specifically suppress the semaphore components and resource multiproc use.

**Comment by chrisfilo** [comment]
This is not intended to be a solution but a temporary measure to restore
reliability of our CI tests.

**Comment by chrisfilo** [comment]
To avoid confusing contributors with multiproc tests timing out I would recommend merging this ASAP and turning those test back on when solution will be found.

**Comment by chrisfilo** [comment]
Happened to me just now on another PR: https://circleci.com/gh/nipy/nipype/1699

**Comment by satra** [comment]
only a temporary merge - let's revert as soon as we figure out the issue. because many people still use multiproc to run things.

**Comment by chrisfilo** [comment]
For sure!

**Pull request merged**
