### PR TITLE
Push to upstream

### PR DESCRIPTION
**Pull request by byvernault**
Dear Nipype Team,

First, thank you for all your work on nipype. It's really great to use this package in Neuro-Imaging.

We have been working at UCL on implementing our three main packages into the nipype framework. We added niftyreg/niftyseg/niftyfit to nipype in our fork of nipype. We are finally ready to push it to your upstream (nipy/nipype). You can see in this pull request all our changes. There are quite a lot because we started this in 2015 but actually, you can probably just looked at the new files in the interfaces and workflows. I am pretty certain that we didn't touched any of the core system of nipype. 

In few words, we added: 
  1) interfaces for niftyreg/niftyfit/niftyseg.
  2) tests and docstring for each interfaces
  2) workflow for niftyreg in nipype/workflows/smri/niftyreg/groupwise. We followed the template from other workflows.

Let us know if you have any questions and if we can help with this request.

Kind Regards,

Ben Yvernault & Marc Modat (@mmodat)
http://cmictig.cs.ucl.ac.uk/

### CODE REVIEW

**Comment by oesteban** [comment]
Hi @byvernault, we'll be very happy to merge the nifty- interfaces in :)

I've been going through the PR quickly, and I see the following problems:

  - There are many interfaces from Nipype modified. I would imagine that all those changes are necessary, but it will be really hard to review all that code. Would it be possible to split this enormous PR into simpler elements? Particularly, it would be nice to have one PR with nifty- interfaces only (cherry-picking from your branch into a new one should work fine here).
  - Seems to contain much Python2 -only code. We'll also need to work on that since Nipype should work on both python 2 and 3.

But yes, we totally want to get your work merged. Please don't hesitate to ping us whenever you need help with this code. Also, joining the gitter channel and dropping questions there might be a good idea to get this done.

**Comment by byvernault** [comment]
Hi @oesteban,

Sure, I can work on splitting all this and test that it works on both python 2 and 3. I will also reorganise the PR to make it simpler. Sorry for this enormous PR, I joined later this project and I should have cleaned it.

Thank you for your answer.

Kind Regards,
Ben

**Comment by mmodat** [comment]
Just as an FYI.
We just forked the main repo in https://github.com/mmodat/nipype and will make simpler PR by adding each package independently.

**Comment by oesteban** [comment]
@mmodat sounds wonderful, we are very looking forward to this addition.

@byvernault, please, do not hesitate to ping us as much as you need :)

**Pull request closed without merging**
