### PR TITLE
Remove 'usedefault' from gm_odf & csf_odf in mrtrix3.EstimateFOD input spec

### PR DESCRIPTION
**Pull request by tclose**
## Summary

Was not able to use original (non-multi tissue) CSD algorithm to estimate fibre orientation distributions as the unexpected (for single-tissue reconstruction) output gm-odf and csf-odf files were being written to the command line.

Fixes # .

## List of changes proposed in this PR (pull-request)

* removed 'usedefault=True' from gm_odf & csf_odf traits of mrtrix3.EstimateFOD input spec
* added .vscode and .history to gitignore

## Acknowledgment

- [ x ] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
This should be resolved by the addition of a new interface. Can you check the docs? Otherwise I can find the PR in a bit.

**Comment by tclose** [comment]
I don't see any new interfaces that look relevant in the docs. Also searched the master branch for 'dwi2fod' and it only came up with the EstimateFOD

**Comment by effigies** [comment]
#3176

**Comment by tclose** [comment]
Ok, thanks

**Pull request closed without merging**
