### PR TITLE
update FSL on CircleCI, fixed tests

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by satra** [comment]
make specs

**Comment by chrisfilo** [comment]
I did but there were no updates...

**Comment by satra** [comment]
i guess default values are not added in the auto tests, only the metadata fields.

**Comment by chrisfilo** [comment]
AFAIK this is ready to merge (so our tests will start passing again!)

**Comment by oesteban** [comment]
Well done guys!

**Pull request merged**
