### PR TITLE
[FIX] update sample_random_points and random_seed type of ProbTrackXBaseInputSpec

### PR DESCRIPTION
**Pull request by mauriliogenovese**
updated random_seed to accept an integer value and sample_random_points to accept a float value

https://github.com/nipy/nipype/issues/3534

### CODE REVIEW

**Comment by effigies** [comment]
Does this stem from a change in probtrackx or has this always been a deficiency of the interface?

**Comment by effigies** [comment]
Sorry, I don't know what you're saying "yes" to.

**Comment by mauriliogenovese** [comment]
I think probtrackx has always been like that, sry I misread your question and I was updating my reply

**Comment by mauriliogenovese** [comment]
I've found some other similar little inconsistencies. It's ok if I propose other pull requests or do you prefer that I just open issues? I'm not too practiced in git

**Comment by effigies** [comment]
Due to the low maintenance level in nipype (nobody has much time to spend on it), it's probably most efficient to open PRs unless it would be more costly to attempt to fix things before discussing them.

It may also be most efficient to copy/fix interfaces in the packages that use them, so that you are not dependent on our release cycle, which is basically unspecified at this point. Anyway, thanks for this.

**Pull request merged**
