### PR TITLE
MRG:Allow extra wait time for Xvfb if needed

### PR DESCRIPTION
**Pull request by blakedewey**
Change to _redirect_x block to allow more wait time for Xvfb if needed. Max wait time could potentially be set in config. Hard coded for now. @chrisfilo, thoughts?

### CODE REVIEW

**Comment by satra** [comment]
sounds reasonable. agree that a config option for this would be good.

**Comment by oesteban** [comment]
+1 to any improvement on headless operations :)

**Comment by blakedewey** [comment]
Added config option "xvfb_max_wait"

**Comment by satra** [comment]
@blakedewey - could we also please update the CHANGES file and add the new option to config.rst?

**Comment by blakedewey** [comment]
@satra should be good now. I changed the docs in config_file.rst. I hope that is the right one.

**Pull request merged**
