### PR TITLE
ENH: SPM NewSegment multi-channel segmentation

### PR DESCRIPTION
**Pull request by jhuguetn**
## Summary

[SPM Segment](https://www.fil.ion.ucl.ac.uk/spm/doc/manual.pdf#page=45) supports including additional images as alternative data channels to help improving the segmentation results of the first/main channel images by providing complementary information (e.g. multimodal images) to the segmentation procedure. 
However, this feature is not (yet) supported by nipype [NewSegment](https://nipype.readthedocs.io/en/latest/api/generated/nipype.interfaces.spm.preprocess.html#newsegment) interface (see `nipype.interfaces.spm.preprocess`).

This PR proposes a modification to the existing `NewSegment` interface to support using several data channels for SPM's segmentation procedure.

As suggested in the [contribution guide](https://github.com/nipy/nipype/blob/master/CONTRIBUTING.md#making-a-change), changes have been successfully tested via `pytest` with the following results:
```
 2734 passed, 230 skipped, 7 xfailed, 15 warnings in 183.65s (0:03:03) 
```

Related issue: https://github.com/nipy/nipype/issues/2342#issuecomment-581879802

## List of changes proposed in this PR (pull-request)
* refactored `NewSegmentInputSpec()` class to support a list of channels
* updated docstring-based examples and new `T2.nii` file added to testing data
* updated tests (see `test_NewSegment_inputs()`

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
@jhuguetn - thank you for this.

we should maintain backwards compatibility for existing scripts/workflows using the current interface. this can be done by making the original inputs mutually exclusive with the new one. (and still supporting the original functionality).

**Comment by jhuguetn** [comment]
Thanks @satra for considering this proposal. 

I see two possible alternatives, 
1. support both original and new inputs in a mutually exclusive way as you suggest, however that -in my opinion- makes the class code a bit messier/longer than it should originally be. 
1. create a brand new Interface (e.g. `MultiChannelNewSegment`) with the changes proposed. 

What you think?

**Comment by satra** [comment]
> create a brand new Interface (e.g. MultiChannelNewSegment) with the changes proposed.

i would be fine with a new interface here.

**Comment by jhuguetn** [comment]
I've just included new changes to my original PR proposal. Now it creates a brand new Interface called `MultiChannelNewSegment' which supports defining multiple channels when running SPM Segment procedure.

**Comment by effigies** [comment]
Is this ready to go?

**Comment by jhuguetn** [comment]
Hi @effigies, it is from my side. Do you plan to include it in the 1.5.0 release?

**Comment by effigies** [comment]
Sounds good. Yes, we'll include it in 1.5.0. That's currently stalled as we try to find time to debug failing tutorials...

**Comment by jhuguetn** [comment]
Great, thanks

**Pull request merged**
