### PR TITLE
REL: 1.1.3

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Prep for 1.1.3 release, targeting Monday, September 24.

Pending merge or postponement decision on:

* [x] #2607
* [x] #2652
* [x] #2701
* [x] #2705

## Release checklist

* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py` and `doc/conf.py`
* [x] Update `doc/documentation.rst` with previous releases

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by satra** [comment]
@effigies  and @kaczmarj - it may be useful to optimize the neurodocker generator if we can. 

for example, can we go back to neurodebian for afni now that a january version is available? we should re-evaluate all of this at the sprint.

**Comment by effigies** [comment]
@djarecka Could you test the tutorials against this branch?

**Comment by effigies** [comment]
@yarikoptic Heads up on a new nipype release scheduled for Monday. This branch should be exactly what's released, unless there are bugs found by the final round of tests.

**Comment by effigies** [comment]
@djarecka Are we good to go?

**Comment by effigies** [comment]
Sounds good. Just shooting for today.

**Comment by djarecka** [comment]
@effigies - everything works fine

**Pull request merged**
