### PR TITLE
[ENH] Sorting out Dockerfiles

### PR DESCRIPTION
**Pull request by oesteban**
Software to be included in this image for tests:
- [x] FSL
- [x] FreeSurfer
- [x] SPM
- [x] ANTs
- [x] AFNI
- [ ] dcm2niix
- [x] nipy
- [x] C3D_affine_tool
- [ ] VTK

Environments:
- [x] python 2.7
- [x] python 3.4
- [x] python 3.5

### CODE REVIEW

**Comment by satra** [comment]
@oesteban - for freesurfer are we including the entire image or breaking out pieces?

**Comment by oesteban** [comment]
@satra entire image

**Comment by oesteban** [comment]
Can we leave dcm2niix and VTK for another PR?

As regards FreeSurfer, is there any place where I can find a lightweight version? (BTW, this upgrades FreeSurfer to v. 6.0.0).

**Comment by oesteban** [comment]
Question:

We have these two docker build commands in the circle.yml:

```
    - docker build -f docker/Dockerfile_py27 -t nipype/nipype_test:py27 . :
        timeout: 1600
    - docker build -f docker/Dockerfile_py35 -t nipype/nipype_test:py35 . :
        timeout: 1600
```

They take ~3 and ~1 min respectively but they are not cached. Do we want to cache them?

**Comment by satra** [comment]
does circle rebuild cache if `docker/Dockerfile_py[27|35]` changes? if so sure.

**Comment by oesteban** [comment]
Yeah, it rebuilds, I'll add caching for them.

**Comment by oesteban** [comment]
@satra what did you have in mind about freesurfer?

**Comment by satra** [comment]
@oesteban - freesurfer has many components and expands out to over 8G. if we just want it for recon-all, we can strip it down to about 500MB. if we want tracula, and cvs, and other tools, then it will grow. 

if circle can handle it, i say we don't touch it right this minute. but for anyone who wants to test it that docker download will be close 15G, no (with FSL and FreeSurfer and AFNI)?

**Comment by oesteban** [comment]
5 GB - https://hub.docker.com/r/nipype/nipype/tags/

**Comment by satra** [comment]
don't worry about it right now.

**Comment by oesteban** [comment]
merge?

**Pull request merged**
