### PR TITLE
REL: 1.5.0

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Prep for new feature release 1.5.0, targeting release on Monday, February 24.

Given that we just released 1.4.2 about a week ago, I'm inclined to hold this one off for any feature PRs that would like to shoot for inclusion.

Require merge or postponement decision on all issues/PRs in https://github.com/nipy/nipype/milestone/38:

* [x] ENH: Add a ``Bandpass`` filter interface under ``algorithms.filters`` #2915 (@oesteban)
* [x] [WIP/ENH] Adds a new interface for AFNI's ``3dMEMA`` command #2953 (@JesseyWright / @oesteban)
* [x] ENH: Add interface for fslorient #2955 (@felixsc1)
* [x] [FIX] Mrtrix3 usedefault issue (#3004) (@matteomancini)
* [x] [DOC] SelectFiles docstring corrected #3041 (@AKSoo)
* [ ] FIX Ants N4BiasFieldCorrection rescale_intensities bug #3139 (@salma1601)
* [x] CI: Test Python 3.8 #3154 (@effigies)
* [x] ENH: Detect values for EulerNumber interface #3173 (@mgxd)

Will try review the open PRs and see if anything is close enough to push on, tomorrow.

## Release checklist

* [ ] Merge pending PRs
* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py`
* [x] Update `doc/interfaces.rst` with previous releases
* [x] Check conda-forge feedstock build (conda-forge/nipype-feedstock#67)
* [ ] Tutorial tests (https://circleci.com/workflow-run/be312bea-8273-47cf-9e52-54257d969422)

## Uncredited authors

The following authors have contributed, but not added themselves to the [`.zenodo.json`](https://github.com/nipy/nipype/blob/master/.zenodo.json) file. If you would like to be an author on Zenodo releases, please add yourself or comment with your preferred publication name, affiliation and [ORCID](https://orcid.org/). If you would like to stop being spammed whenever I'm the one doing releases, let me know, and I'll add you to a blacklist.

No entry to sort: cdla (@cdla)
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Victor Férat (@vferat)
No entry to sort: Niklas Förster (@niklasfoe)
~~No entry to sort: Adam Kimbler (@adamkimbler)~~
No entry to sort: Kirstie Whitaker (@KirstieJane)
No entry to sort: Pablo Polosecki (@polosecki)
No entry to sort: Ami Tsuchida
No entry to sort: Daniel Brenner (@brennerd11)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Kevin Sitek (@sitek)
No entry to sort: Luke Bloy (@bloyl)
No entry to sort: Martin Luessi (@mluessi)
No entry to sort: steve (@steve19922)
No entry to sort: Charl Linssen (@turingbirds)
No entry to sort: Félix C. Morency (@fmorency)
~~No entry to sort: Jonathan R. Williford (@williford)~~
No entry to sort: Michiel Cottaar (@MichielCottaar)
No entry to sort: Regina Kim (@reginakim)
No entry to sort: Valentin Haenel (@esc)
No entry to sort: Xu Wang
No entry to sort: maedoc (@maedoc)

I am unable to find GitHub handles for Ami Tsuchida or Xu Wang.

Apologies also to anybody who may have 

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by adamkimbler** [comment]
Hey, 

Sorry for the delay in submitting this.

{
     "affiliation": "Florida International University",
     "name": "Kimbler, Adam",
     "orcid": "0000-0001-5885-9596"
}

**Comment by effigies** [comment]
@miykael @djarecka Any chance one of you could have a look at https://circleci.com/workflow-run/6eba71d4-5cb8-4711-b95a-83d7393dd71c?

For reference, here's the diff between that branch and `master`: https://github.com/miykael/nipype_tutorial/compare/master...effigies:rel/1.4.1

**Comment by effigies** [comment]
Bump for @miykael and @djarecka, in case this got lost in your notifications last night.

**Comment by oesteban** [comment]
It could be interesting to push #3180 into 1.5.0, wdyt @effigies ?

**Comment by effigies** [comment]
Sure. I don't see much prospect of fixing the tutorials soon, so the release is held up for now. Squeeze in as you like.

**Comment by williford** [comment]
Mark,

Could you blacklist me? My contribution was insignificant and I give up any
rights to my contribution(s) (you can license or re-license however you
want).

Thanks!
Jonathan

**Comment by oesteban** [comment]
While we figure out the notebooks problem, could we maybe push an RC?

**Comment by effigies** [comment]
Sure.

**Comment by effigies** [comment]
@oesteban @satra I'm planning on releasing 1.5.0rc1 from this branch, once the feedstock build is fixed. Or, if we don't care about getting release candidates on conda, I can just go ahead...

**Comment by oesteban** [comment]
I'm fine either way. I don't think we really need this RC other than in Pypi

**Comment by effigies** [comment]
Sorry, should have updated. Rerendering the feedstock worked. 1.5.0rc1 is on PyPI and conda-forge.

**Pull request merged**
