### PR TITLE
WIP: Interfaced Workflows and GraftWorkflow

### PR DESCRIPTION
**Pull request by oesteban**
These workflows provide automatic input/output nodes generation, with some other utilities such as fast connection (avoiding to specify the connecting fields).

GraftWorkflow is intended to create evaluation workflows, where all the inputs are the same but several different methods are to be compared, stacking the outputs in lists.

download

Two additional interfaces have been coded: CollateInterface and MultipleSelectInterface. These interfaces multiplex/demultiplex outputs/inputs respectively.
- [x] InterfacedWorkflow class
- [x] GraftWorkflow class
- [x] CollateInterface and MultipleSelectInterface (mux/demuxer)
- [x] doctests
- [x] regression tests
- [x] ~~open new _experimental_ modules within distribution~~
- [x] documentation, on the same vein of iterables, mapnodes, etc

EDIT [Dec 31, 2015]:
After commenting with @chrisfilo,  we have added the following features/requirements for this PR:
- [ ] Making InterfacedWorkflows a true blackbox (like Nodes are):
  - [x] Do not expose (in/out)putports of internal nodes as inputs/outputs
  - [ ] Do not allow inserting sub-workflows with connections to external nodes.

Once we get these InterfacedWorkflows to work, we will then focus on #1299.

### CODE REVIEW

**Comment by chrisfilo** [comment]
Indeed this looks very cool. Maybe we could finish this off during the sprint next month?

**Comment by oesteban** [comment]
Actually I was planning a parallel sprint by myself to close my PRs in these dates. So, surely :)

**Comment by oesteban** [comment]
@satra, @chrisfilo, could you give me some hints about what kind of regression tests we want to have?

I have some ideas, for instance, the mux/demux nodes at input and output of the workflow are implemented with interfaces under utility. Their functions are clear, so tests are easy to design. However, at the highest level, what could be the tests?

**Comment by satra** [comment]
you could do tests on the flattened graph or the execution graph in terms of number of nodes. also you could create a set of dummy interfaces to test that the comparators are working.

**Comment by chrisfilo** [comment]
Could you add some examples to the documentation first so we could better understand the use cases/motivation?

**Comment by oesteban** [comment]
@chrisfilo I have added a example in the docs.

** BTW, how could I generate the graphs corresponding to the examples and automatically insert it in the generated html?

**Comment by oesteban** [comment]
up!

**Comment by oesteban** [comment]
Edited general description of this PR

**Comment by djarecka** [comment]
@oesteban - are you still working on this pr?

**Comment by oesteban** [comment]
I'll reopen if I find the time to finish up.

**Pull request closed without merging**
