### PR TITLE
[ENH] Enable num_threads for antsAffineInitializer

### PR DESCRIPTION
**Pull request by oesteban**
This PR just enables the general control for number of threads for
this tool. I just learned that it works differently depending on it
https://github.com/stnava/ANTs/issues/444

### CODE REVIEW

**Comment by satra** [comment]
@oesteban - this likely needs a make specs update.

**Comment by oesteban** [comment]
You got it. Felt like a newbie when I read your comment :P

**Comment by satra** [comment]
@oesteban - we will address this before 1.0. better testing is coming to nipype (https://github.com/kaczmarj/neurodocker).

**Comment by oesteban** [comment]
Rerun the failing builds of Travis (due to apt's hiccups). This is ready to merge.

**Pull request merged**
