### PR TITLE
REL: 1.1.9

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Prep for 1.1.9 release, targeting Monday, Feberuary 25.

Pending merge or postponement decision on:

* [x] #2857 (@hstojic)
* [x] #2861 (@hstojic)
* [x] #2870 (@hstojic)
* [x] #2877 (@mgxd)
* [x] #2878 (@rciric)

Just a note that I don't consider any of these blocking, so if I don't hear from their authors by tomorrow evening I will remove the milestone. Feel free to set it to [1.2.0](https://github.com/nipy/nipype/milestone/31) if you think you can come back to it in the next month, or [future](https://github.com/nipy/nipype/milestone/7) if you still plan to come back to it, but don't foresee hitting next month's deadline. Older/inactive PRs may be deemed [orphaned](https://github.com/nipy/nipype/blob/master/CONTRIBUTING.md#issue-labels).

## Release checklist

* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py` and `doc/conf.py`
* [x] Update `doc/documentation.rst` with previous releases
* [x] Tutorial tests (@djarecka)

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
The following contributors since 1.1.8 do not have entries in the `.zenodo.json`:

* @gpiantoni 
* @jguillon 
* @mr-c 

Please add yourselves, if you're interested.

From a scan through the full shortlog, I also notice the following people don't have entries:

* @cdla 
* @dmordom 
* @rciric 
* @leej3 
* @anibalsolon 
* @skoudoro 
* @qtabs 
* @JDWarner 
* @62442katieb 
* @niklasfoe 
* @oliver-contier 
* @afni-dglen 
* @belevtsoff 
* @rku 
* @KirstieJane 
* @mattcieslak 
* @margulies 
* @polosecki
* @sitek 
* @atsuch
* @anbai106 
* @mluessi 
* @kchawla-pi 
* @vanandrew 
* @brennerd11 
* @steelec 
* @esc 
* @fmorency 
* @iglpdc 
* @sealhuang 
* @MichielCottaar 
* @abelalez 
* @maedoc 
* @reginakim 
* @turingbirds
* @williford 
* @servoz 

If any of you would like to be listed properly as authors, please add your information to the Zenodo file. Or just post the name you'd like to be cited with, your affiliation and your ORCID, and I'll add you.

**Comment by kchawla-pi** [comment]
Name: Kshitij Chawla (kchawla-pi)
Affiliation: INRIA-Saclay, Team Parietal
ORCID: 0000-0002-7517-6321

**Comment by effigies** [comment]
Thanks @kchawla-pi.

**Comment by effigies** [comment]
@qtabs @gladomat We have a script that reorders Zenodo entries by lines contributed, and it looks like it removed Paul's entry. I checked the `shortlog` and don't see him as the author on any commits? Could you clarify the contribution? If he's been a co-author, but all the commits were authored by Alejandro, I can add him to a list of authors who get appended just prior to the last author (we have a few of these whose apparent contributions have disappeared due to reorganizations).

**Comment by qtabs** [comment]
> @qtabs @gladomat We have a script that reorders Zenodo entries by lines contributed, and it looks like it removed Paul's entry. I checked the `shortlog` and don't see him as the author on any commits? Could you clarify the contribution? If he's been a co-author, but all the commits were authored by Alejandro, I can add him to a list of authors who get appended just prior to the last author (we have a few of these whose apparent contributions have disappeared due to reorganizations).

Yes, sorry! Although I pushed the commits we worked together in the implementation. Can you please add him to the appended list? I don't think he cares about the ordering too much. Thanks :).

**Comment by servoz** [comment]
Name: Eric Condamine (servoz)
Affiliation: CNRS, UMS3552 IRMaGe
ORCID: 0000-0002-9533-3769

**Comment by 62442katieb** [comment]
Name: Katherine Bottenhorn (62442katieb)
Affiliation: Florida International University
ORCID: 0000-0002-7796-8795

**Pull request merged**
