### PR TITLE
FIX: Set networkx max version until 2.0 fixes are finalized

### LINKED ISSUE #2194: Master is broken
It looks like the travis build is failing on master: https://travis-ci.org/nipy/nipype/branches |  https://travis-ci.org/nipy/nipype/builds/274426849

And indeed my tests that depend on nipype master recently started failing too: https://travis-ci.org/mwaskom/lyman/builds/278793733

### PR DESCRIPTION
**Pull request by effigies**
Fixes #2194.

Changes proposed in this pull request
- Set networkx max version of 1.11

### CODE REVIEW

**Comment by effigies** [comment]
Looks like Travis just really hates afni.Hist all the sudden. So much for this working first.

**Comment by satra** [comment]
i can't see anything in the code that would be weird. for the time being could you temporarily remove that particular test just to check travis?

also since circle runs on py36 with dependencies, it's weird that the error condition on travis is on the closest cell that circle runs on.

**Comment by effigies** [comment]
@satra Note that all `INSTALL_DEB_DEPENDENCIES=true` lines are failing. Wonder if it's a neurodebian problem.

https://travis-ci.org/nipy/nipype/builds/278944845

**Comment by effigies** [comment]
What test is actually failing? The doctest?

**Comment by satra** [comment]
re: doctest - i believe so.

neurodebian has not updated it since 2016, so i don't know what's going on there.

**Comment by effigies** [comment]
Now it's skullstrip. Which I think are the two interfaces with  redirect_x.

**Comment by satra** [comment]
nothing is running though in those tests, just an initialization. i wonder whether the afni_vcheck command is failing. trying out now in a debian:stretch container.

**Comment by effigies** [comment]
I think that's it. I can't hit https://afni.nimh.nih.gov/

**Comment by satra** [comment]
just verified locally that it's `afni_vcheck` that's failing.

**Comment by effigies** [comment]
I think adding a <30s timeout would be a good idea. Nipype shouldn't depend
on the AFNI web server's availability.

**Comment by satra** [comment]
timeout exists in subprocess for python 3, but python 2 needs some extra work.

**Comment by effigies** [comment]
Is there another way to get the version? I couldn't find a flag to avoid
fetching the url.

**Comment by satra** [comment]
i think this should fix it: see: https://github.com/djarecka/nipype/pull/3

**Comment by effigies** [comment]
Looks reasonable, but I think Dorota is afk this weekend. Maybe just create
a PR from your branch?

**Comment by effigies** [comment]
Closing in favor of #2196.

**Pull request closed without merging**
