### PR TITLE
[FIX] Errors parsing ``$DISPLAY``

### LINKED ISSUE #2362: issue with MIPAV module
Dear all,
I've tried to run the example on MP2RAGE-skullstripping  http://nipype.readthedocs.io/en/latest/users/examples/smri_cbs_skullstripping.html with nipype 0.14.0 and CBStools version 3.0. I use a conda environment based on python 2.7.

Here is the error message:
Traceback: 
Traceback (most recent call last):
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 43, in run
    node.run(updatehash=updatehash)
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1063, in run
    env['DISPLAY'] = config.get_display()
  File "/home/raid1/fbeyer/local/miniconda2/envs/nip14/lib/python2.7/site-packages/nipype/utils/config.py", line 286, in get_display
    ndisp = int(sysdisplay.split(':')[-1])
ValueError: invalid literal for int() with base 10: '0.0'

When running the MIPAV command separately it works fine. 

Do you have an idea what could be the reason for this?
Best
Frauke

### PR DESCRIPTION
**Pull request by oesteban**
The format for ``$DISPLAY`` is ``<host>:<display>[.<screen>]``. When
screen is specified, the config object fails.

This patch fixes #2362

EDIT: extra addons

* [x] New parametric test for the new feature
* [x] Added tests mocking Mac and non-Mac systems
* [x] Skip tests that would always fail in Mac systems

### CODE REVIEW

**Comment by oesteban** [comment]
Experts on Circle and Travis: why I can't redefine environment variables (`$DISPLAY` in particular) in any of them? I've tried both `os.environ` and monkeypatching. Both work locally, but fail on CI engines.

cc @satra

**Comment by oesteban** [comment]
I still need to find out why tests work locally (whether it is containerized or not does not really matter) but consistently fails in Travis AND Circle. This one will need to wait.

**Comment by oesteban** [comment]
Seems to work now!

**Comment by effigies** [comment]
@oesteban Can you cancel https://circleci.com/gh/oesteban/nipype/942?

**Pull request merged**
