### PR TITLE
MAINT: Permit recent nilearns

### LINKED ISSUE #2791: Nilearn 0.5.0 breaks tests
### Summary
The latest release of nilearn broke master.

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Fixes #2791.

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
nilearn 0.4.2 to 0.5.0 was a pretty huge change. While they had two pre-releases, it looks like our nilearn tests don't run on Travis, which is where we do our pre-release tests.

So I'm pinning to the pre-releases, to help narrow down the window in which the change happened. It's unclear whether this is a nilearn bug.

**Comment by effigies** [comment]
I've decided this is a nilearn bug: nilearn/nilearn#1891, introduced in nilearn/nilearn#1711.

We can also try to accommodate this version, by making sure that we pass in appropriate `dtype`s, but I think it's more appropriately handled on their end.

**Comment by effigies** [comment]
Last two commits verify the source of the failure. (I cancelled all but the pytest jobs.)

**Comment by satra** [comment]
0.5.1 was released 7 days ago, perhaps this can now be re-tested and merged?

**Comment by effigies** [comment]
Rebased. Doubt it'll work.

**Comment by effigies** [comment]
Nope. They did some weird stuff and were unwilling to revert, and I haven't found time to dig through their code and figure out how to restore functionality.

**Comment by effigies** [comment]
@satra Good to go?

**Pull request merged**
