### PR TITLE
Camino out_file naming

### PR DESCRIPTION
**Pull request by mick-d**
In the track interface, no provision was made when the out_file name was specified to rename the out_file accordingly. This is now corrected.

### CODE REVIEW

**Comment by mick-d** [comment]
Checking Travis output the build was actually fine. Does this PR look ok?

**Comment by oesteban** [comment]
@mick-d I re-run the failing test and now it's ok ;)

**Comment by mick-d** [comment]
Great, thanks! Then it's ok to merge?

**Comment by satra** [comment]
missed a CHANGES file. i'll update it.

**Comment by mick-d** [comment]
Thanks @satra. I did not want to clutter the CHANGES file with such a small change but glad to hear it is worth notifying.

**Pull request merged**
