### PR TITLE
doc: update changes

### PR DESCRIPTION
**Pull request by mgxd**
since we've all been a little sloppy with updating during PRs

### CODE REVIEW

**Comment by satra** [comment]
@mgxd - actually mostly i've been sloppy. the current policy is to update CHANGES after pull requests are merged.

**Comment by satra** [comment]
merge with master and update changes again - a bunch of pull-requests have been merged.

https://github.com/nipy/nipype/pulls?q=is%3Apr+is%3Aclosed

just go down the list and for each one add a 1 line summary.

**Comment by satra** [comment]
need to merge this again.

**Comment by mgxd** [comment]
Should be all set - ready to merge?

for future sake, I should probably just commit directly to master when changing CHANGES

**Pull request merged**
