### PR TITLE
new interface for Bru2

### PR DESCRIPTION
**Pull request by TheChymera**
Following up on #1293

### CODE REVIEW

**Comment by chrisfilo** [comment]
It seem that there are some indentation errors in your code. Also please run `make specs` to generate more tests and add a line to changelog.

Thanks! Looking forward to having this in nipype!

**Comment by TheChymera** [comment]
Is this your ChangeLog? https://github.com/nipy/nipype/blob/master/CHANGES

**Comment by chrisfilo** [comment]
Yes!

**Comment by TheChymera** [comment]
@chrisfilo  hey, so is this good to go? I see it is still failing one test, but I can't understand why. Can you help me out?

**Comment by chrisfilo** [comment]
Could you merge or rebase master? This should make test run.

**Pull request closed without merging**
