### PR TITLE
BF(workaround): fix permissions for use_resources tests script during installation

### PR DESCRIPTION
**Pull request by yarikoptic**
I don't like it but it seems to work

ppl are saying that setuptools preserves permissions... might be worth migrating from plain distuils.setup

### CODE REVIEW

**Comment by satra** [comment]
@yarikoptic -  we have got rid of `distutils` in relies directly on `setuptools`. can you see if this is still an issue, and if so if there is a `setuptools` way of doing this without using `distutils`?

**Comment by oesteban** [comment]
I just tried this with a conda environment, installing from pypi and without any special umask and permissions after install are 0775.

**Comment by djarecka** [comment]
@yarikoptic - are you still working on it? do we still experience some problems related to it?

**Comment by djarecka** [comment]
@yarikoptic ping

**Comment by oesteban** [comment]
I don't think this is necessary anymore after the refactoring of the resource monitor. Please correct me if I'm wrong.

**Pull request closed without merging**
