### PR TITLE
[DOC] Replace initialism typo in comment with intended phrase

### PR DESCRIPTION
**Pull request by mr-c**
## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by mr-c** [comment]
Thank you @effigies

**Comment by effigies** [comment]
Thank you for the fix!

**Comment by satra** [comment]
@mr-c - really funny to see this. i know exactly what you were searching for :) 

on the real cwl related note, we are working on a rewrite of the nipype engine as a new project called pydra. once it can actually stand and walk (our hope is by end of feb), we would love to chat about cwl integration a little more. that's definitely in the plans for pydra.

**Comment by mr-c** [comment]
@satra You caught me! :-)

> pydra

Cool! I'll ping you the first week of March :-D

**Pull request merged**
