### PR TITLE
FIX: Remove asynchronous chdir callback

### PR DESCRIPTION
**Pull request by stilley2**
## Summary

Remove the asynchronous chdir callback in the multiproc plugin

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
The problem that led to this, though, was something calling `getcwd()` from a deleted directory. Has that root cause gone away?

**Comment by oesteban** [comment]
It should be. Virtually any `getcwd()` call from a worker that was initiated in a nonexistent folder would crash. But that problem is addressed by the init hook included in that old PR. The chdir being removed is the result of my desperation at that moment.

**Comment by effigies** [comment]
Okay. I'll defer to your memory on that one.

**Comment by effigies** [comment]
@oesteban I was assuming you were going to merge this. Is there a hold-up, or were you waiting for a second approval?

**Comment by oesteban** [comment]
Sorry for the delay

**Pull request merged**
