### PR TITLE
[wip]Fix/deprecated 2551 (closes #2551 #2508)

### LINKED ISSUE #2508: LSFPlugin sets ignore_exception=True on line 57 of lsf.py plugin causing workflow to crash due to deprecation
The _is_pending function in the LSFPlugin when running the command sets the ignore_exception=True on line 57.  See below:

```
def _is_pending(self, taskid):
        """LSF lists a status of 'PEND' when a job has been submitted but is
        waiting to be picked up, and 'RUN' when it is actively being processed.
        But _is_pending should return True until a job has finished and is
        ready to be checked for completeness. So return True if status is
        either 'PEND' or 'RUN'"""
        cmd = CommandLine(
            'bjobs', resource_monitor=False, terminal_output='allatonce')
        cmd.inputs.args = '%d' % taskid
        # check lsf task
        oldlevel = iflogger.level
        iflogger.setLevel(logging.getLevelName('CRITICAL'))
        result = cmd.run(ignore_exception=True)
        iflogger.setLevel(oldlevel)
        # logger.debug(result.runtime.stdout)
        if 'DONE' in result.runtime.stdout or 'EXIT' in result.runtime.stdout:
            return False
        else:
            return True
```
This results in workflows not executing with newer versions of nipype (I'm using version 1.0.1) exiting with the following error:

> TraitError: Input ignore_exception in interface CommandLine is deprecated. Will be removed or raise an error as of release 1.0.0 

I removed ```ignore_exception=True``` from my copy of nipype and was able to execute the workflow with no problems.

### LINKED ISSUE #2551: deprecated traits in BaseInterfaceInputSpec and CommandLineInputSpec
### Summary

we have two traits that are marked ad `deprecated='1.0.0'` in `interfaces/base/specs.py`:
- [ignore_exception in BaseInterface](https://github.com/nipy/nipype/blob/master/nipype/interfaces/base/specs.py#L322)
- [terminal_output in CommandLine](https://github.com/nipy/nipype/blob/master/nipype/interfaces/base/specs.py#L374)

At the same time we're using these traits in some plugins, e.g. [here](https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/condor.py#L57) and it leads to [errors](https://neurostars.org/t/traiterror-for-condor-plugin/1567/5)

I'm not sure why we wanted to deprecate these traits, and if we still want to do it now, or we want to set a different nipype version.

Related to #2508

### PR DESCRIPTION
**Pull request by djarecka**
removing `terminal_output` and `ignore_exception`when creating `CommandLine` instances. These traits are deprecated in `CommandLineInputSpec`

Closes #2551 
Closes #2508

### CODE REVIEW

**Comment by effigies** [comment]
Ah, `terminal_output` is still a valid argument to a `CommandLine` interface and `ignore_exception` is still valid for `BaseInterface`, and they do valid things. It's just that they are no longer going to be inputs.

See:

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L173-L174

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L906

So what's happening at `.run(ignore_exception=True)` is that it's hitting:

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L475

I think the easiest thing would be to add `ignore_exception` to `BaseInterface.run`:

```Python
def run(self, cwd=None, ignore_exception=None, **inputs):
    if ignore_exception is None:
        ignore_exception = self.ignore_exception
```

And then just change this line to use the local variable `ignore_exception`:

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L534-L535

We should also remove:

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L922-L925

and

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/core.py#L953-L955

**Comment by effigies** [comment]
So I would actually undo all of the changes in the current diff, and replace

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/specs.py#L321-L328

with `BaseInterfaceSpec = TraitedSpec`. And just remove this block:

https://github.com/nipy/nipype/blob/a1ab5181370b69490df151838187edf9b0382c44/nipype/interfaces/base/specs.py#L367-L381

This will require a huge `make specs`, and probably some doctest updates.

**Comment by djarecka** [comment]
I'm completely confused. Why do we deprecate these traits, what does it actually mean? we just want to use it differently? only to some methods?

**Comment by effigies** [comment]
I'm pretty sure this was @oesteban deprecating, but the reason is that they make more sense as attributes than as inputs to be set in the input spec. For instance, nobody passes `ignore_exception` from one node to another. So the idea is just to remove the traits and anything that tries to set them while keeping the old behavior.

**Comment by djarecka** [comment]
Ok, so I understand that should remove from input, but be sure that it can be passed to all methods that are using them and to `__init__` (this is already done).

I will revert my changes and try again

**Comment by djarecka** [comment]
I added bot `ignore_exception` and `terminal_output` to `run` method. If you don't want `terminal_output` to be chosen when calling `run`, let me know.

**Comment by djarecka** [comment]
I added `ignore_exception` to `run` method. I was wondering if we also want to have `terminal_output` in `run` (and pass to `run_interface` etc.) but probably it's enough that it can be set in `__init__`. Also, shouldn't we have a different default value different, not `None`? so we can remove this [if](https://github.com/djarecka/nipype/blob/22e9dcaee191814fb68100b68b1fc40fa53dbcfb/nipype/interfaces/base/core.py#L923) and we always have `self.terminal_output`.

**Comment by effigies** [comment]
> I'm not sure about removing ignore_exception and termianl_output from specs.py. I think it might be good to keep it this error for some time.

Sure. It at least gives an informative error. We may want to set a milestone to remove it, just so we don't forget, but that's fine with me. @satra do you agree?

> Also, shouldn't we have a different default value different [for `terminal_output`], not `None`?

Doing it the way we currently are allows a subclass to set a different default like so:

```Python
class NewCommand(CommandLine):
    _terminal_output = 'file_stdout'
```

If we set a default in `__init__`, the subclass would have to override `__init__` to change the default.

So I would keep it as is.

**Comment by satra** [comment]
@effigies - fine with me.

**Comment by effigies** [comment]
Any preferred timeline? 1.1? 1.2? Given that we've only seen two issues, both from internal bugs, not external use of these inputs, I think we can fully remove them after a reasonably short interval.

**Comment by satra** [comment]
let's do 1.1

**Comment by satra** [comment]
we can schedule 1.1 for end of june, right after hbm

**Pull request merged**
