### PR TITLE
fix: do not create a nipype folder in the home directory by default

### PR DESCRIPTION
**Pull request by satra**
Changes proposed in this pull request
- Nipype by default should be stateless and not create any change outside of the directory it is called from.

### CODE REVIEW

**Comment by oesteban** [comment]
We probably should also provide a system-wide way to configure settings, _a la_ matplotlib and do not use the `~/.nipype` anymore. WDYT?

**Comment by satra** [comment]
people can still use that location, just that we don't create it by default. the default config is the one that comes from the library.

**Comment by oesteban** [comment]
Yes -- the idea is to limit the config sources:
- Installation wide (like matplotlib, under nipype installation folder in pythonpath)
- Run-wide: at the working directory level.

**Comment by satra** [comment]
@oesteban - we have always had that.  three locations: (in the nipype code, ~/.nipype, cwd). 

however, after this PR, it will not write a file by default in ~/.nipype. but in all cases, local always supersedes the other two.

**Pull request merged**
