### PR TITLE
[MAINT] Outsource checks of inputs from interface

### PR DESCRIPTION
**Pull request by oesteban**
Another PR removing stuff from the interface class definition. It also adds more precise exceptions.

### CODE REVIEW

**Comment by effigies** [comment]
Hi, just a reminder that the 1.1.8 release is targeted for January 28. Please let us know if you'd like to try to finish this up for that release.

**Comment by oesteban** [comment]
This one would be good to have in 1.1.8. I'll try to resolve conflicts ASAP

**Comment by effigies** [comment]
If you can wait on #2855, that should fix Travis.

**Comment by effigies** [comment]
This pull request is "orphaned," which means it has been deemed to be abandoned by its original author. Orphaned pull requests have not been rejected, and we hope that if a user sees one that will meet their needs with a little work, that they will fork it and open a new pull request (or, in the case of the original author, reopen the original PR).

We ask that all adopted PRs be updated to merge or rebase the current master. If you would like to adopt a PR and need help getting started, any of a number of contributors will be happy to help.

**Pull request closed without merging**
