### PR TITLE
REF: Simplify checkT1s

### PR DESCRIPTION
**Pull request by effigies**
A number of cleanups I saw while looking at #1431.

* This uses nibabel instead of SimpleITK to determine image shape. SimpleITK is still a dependency in two functions in nipype/workflows/smri/freesurfer/utils.py.
* From what I could see, the conversion from `.mgz` to `.nii` was to allow SimpleITK to load the file, so I removed it.
* I used list/generator comprehensions to reduce indentation levels and separate unrelated calculations.

@dgellis90 Can you verify that this still behaves as expected in your tests?

Minor change, so forgoing a CHANGES entry unless otherwise instructed.

### CODE REVIEW

**Comment by dgellis90** [comment]
@effigies The workflow still performs as expected with your changes.

**Comment by effigies** [comment]
Great! Thanks for the quick feedback.

Unrelated to this PR (except insofar as I want to get rid of the SimpleITK dependency), could I get some inputs and results to [center_volume](https://github.com/nipy/nipype/blob/master/nipype/workflows/smri/freesurfer/utils.py#L496-L510) and [recodeLabelMap](https://github.com/nipy/nipype/blob/master/nipype/workflows/smri/freesurfer/utils.py#L513-L567)? These should be pretty easy to rewrite with nibabel, as long as I can check my work.

**Comment by dgellis90** [comment]
@effigies No problem! Here is an example with inputs and outputs that uses both: https://www.dropbox.com/s/ovmwprr71lcbi87/recodingexample.tar.gz?dl=0
Let me know if you need anything else.

**Comment by effigies** [comment]
Do you have some inputs that have an affine matrix that doesn't look like this?

    1 0 0 a
    0 1 0 b
    0 0 1 c
    0 0 0 1

I want to understand `center_volume`. Right now it looks like the algorithm just sets `[a, b, c] = [±dim1/2, ±dim2/2, ±dim3/2]`, but that may simply be a consequence of there being no rotation or scaling.

Incidentally, this seems odd to me, and I want to verify that your goal really is just to adjust the affine matrix, and not to translate the contents of the data array such that you have a nice affine matrix. The consequence of `center_volume` seems to be to put it out of alignment with other files from the same subject. Admittedly, I haven't looked closely at where the resulting files are used, so this could be a dumb question.

**Pull request merged**
