### PR TITLE
FIX adapting mp2rage masking interface to new parameter names in cbstools 3

### LINKED ISSUE #1473: JistIntensityMp2rageMasking interface incompatible with current CBS Tools release
For the command underlying the interface mipav.JistIntensityMp2rageMasking the parameter names have changed in the current CBS Tools release, which makes the interface fail. I meant to do a PR but then saw the mipav/developer.py file is autogenerated and should not be be edited. 

These would be the required changes:
https://github.com/nipy/nipype/compare/master...juhuntenburg:fix/cbstools_params

### PR DESCRIPTION
**Pull request by juhuntenburg**
Fixes #1473 .

Changes proposed in this pull request
- Adapting parameter names in MIPAV interface for MP2RAGE background masking to the names used in the current cbstools version.

### CODE REVIEW

**Comment by juhuntenburg** [comment]
When I run 'make check-before-commit' I get the following error, can anyone help me how to fix this?

```
Traceback (most recent call last):
  File "tools/checkspecs.py", line 15, in <module>
    from nipype.interfaces.base import BaseInterface
  File "/home/raid3/huntenburg/workspace/nipype/nipype/__init__.py", line 49, in <module>
    from .pipeline import Node, MapNode, JoinNode, Workflow
  File "/home/raid3/huntenburg/workspace/nipype/nipype/pipeline/__init__.py", line 10, in <module>
    from .engine import Node, MapNode, JoinNode, Workflow
  File "/home/raid3/huntenburg/workspace/nipype/nipype/pipeline/engine/__init__.py", line 12, in <module>
    from .workflows import Workflow
  File "/home/raid3/huntenburg/workspace/nipype/nipype/pipeline/engine/workflows.py", line 41, in <module>
    from ...interfaces.base import (traits, InputMultiPath, CommandLine,
  File "/home/raid3/huntenburg/workspace/nipype/nipype/interfaces/__init__.py", line 12, in <module>
    from .io import DataGrabber, DataSink, SelectFiles
  File "/home/raid3/huntenburg/workspace/nipype/nipype/interfaces/io.py", line 40, in <module>
    from .base import (
  File "/home/raid3/huntenburg/workspace/nipype/nipype/interfaces/base.py", line 34, in <module>
    from packaging.version import Version
ImportError: No module named packaging.version
Makefile:73: recipe for target 'specs' failed
make: *** [specs] Error 1
```

**Comment by effigies** [comment]
Can you do `pip install packaging`?

**Comment by juhuntenburg** [comment]
Thanks that solved it. But here's a new error...
```
huntenburg@ilz:~/workspace/nipype > make check-before-commit 
Checking specs and autogenerating spec tests
env PYTHONPATH=".:" python tools/checkspecs.py
Traceback (most recent call last):
  File "tools/checkspecs.py", line 424, in <module>
    ic.check_modules()
  File "tools/checkspecs.py", line 380, in check_modules
    bad_specs = self.test_specs(m)
  File "tools/checkspecs.py", line 204, in test_specs
    __import__(uri)
  File "/home/raid3/huntenburg/workspace/nipype/nipype/algorithms/mesh.py", line 25, in <module>
    from ..interfaces.vtkbase import tvtk
  File "/home/raid3/huntenburg/workspace/nipype/nipype/interfaces/vtkbase.py", line 30, in <module>
    from tvtk.api import tvtk
  File "/usr/lib/python2.7/dist-packages/tvtk/api.py", line 11, in <module>
    from tvtk.tvtk_access import tvtk
  File "/usr/lib/python2.7/dist-packages/tvtk/tvtk_access.py", line 54, in <module>
    from tvtk.tvtk_classes import tvtk_helper
  File "/usr/lib/python2.7/dist-packages/tvtk/tvtk_classes.zip/tvtk_classes/tvtk_helper.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/tvtk/tvtk_base.py", line 17, in <module>
    from traitsui.api import BooleanEditor, RGBColorEditor, FileEditor
  File "/usr/lib/python2.7/dist-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "/usr/lib/python2.7/dist-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "/usr/lib/python2.7/dist-packages/traitsui/editors/api.py", line 16, in <module>
    from .boolean_editor import BooleanEditor
  File "/usr/lib/python2.7/dist-packages/traitsui/editors/boolean_editor.py", line 35, in <module>
    from .text_editor import ToolkitEditorFactory as EditorFactory
  File "/usr/lib/python2.7/dist-packages/traitsui/editors/text_editor.py", line 64, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "/usr/lib/python2.7/dist-packages/traits/has_traits.py", line 426, in __new__
    mhto = MetaHasTraitsObject( cls, class_name, bases, class_dict, False )
  File "/usr/lib/python2.7/dist-packages/traits/has_traits.py", line 580, in __init__
    value.replace_include( view_elements )
  File "/usr/lib/python2.7/dist-packages/traitsui/view.py", line 449, in replace_include
    self.content.replace_include( view_elements )
  File "/usr/lib/python2.7/dist-packages/traitsui/group.py", line 293, in replace_include
    view_elements.content[ id ] = item
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 3040, in __setitem__
    raise excp
traits.trait_errors.TraitError: Each key of the 'content' trait of a ViewElements instance must be a value of type 'str', but a value of u'options' <type 'unicode'> was specified.
Makefile:73: recipe for target 'specs' failed
make: *** [specs] Error 1
```

**Comment by effigies** [comment]
That one's new to me. I'd guess either traits or future might need updating, but no guarantees it will help:

```Shell
pip install traits>=4.6 future>=0.16.0
```

**Comment by juhuntenburg** [comment]
Unfortunately not, same error.

**Comment by satra** [comment]
@juhuntenburg - this clearly looks like an interaction with vtk. any chance of testing this out in the nipype docker container? or in a conda environment? 

in the meantime to get these changes merged, i've sent you a pull-request with the necessary changes.

**Comment by juhuntenburg** [comment]
@satra Thanks, i merged your PR and pull to my local branch, but still get the same error when running `make check-before-commit`

**Comment by satra** [comment]
another PR to resolve the ica_aroma conflict. this will not resolve the issue with `make specs`. that unfortunately is coming from some conflict with vtk.

**Comment by juhuntenburg** [comment]
Ok, thanks @satra , i will try out with the nipype docker container later!

**Comment by satra** [comment]
@juhuntenburg - only if you wish to see that make specs runs fine outside your environment or for future PRs. if you are coming to vancouver, we should figure out what in your environment is really causing the issue. the reason we ask people to use conda or docker is to isolate the environment and control it as much as possible.

**Pull request merged**
