### PR TITLE
[DOC] Update links to user and developer help forums

### PR DESCRIPTION
**Pull request by KirstieJane**
## Summary

I was trying to find the right place to ask a question and these links were both broken so I figured I'd send a little PR to update the two places to ask questions as linked from the index bar.

*updated*: I've also done a quick search for other instances of the old mailing list link and updated those.

Additionally I've added the gitter and slack links. Happy to remove those if you don't want to provide so many options!

Please disregard this pull request if this isn't correct or helpful! Very happy to adapt anything that's needed.

## List of changes proposed in this PR (pull-request)

Changed links:

* http://neurostars.org/t/nipype
 ---> https://neurostars.org/search?q=nipype
* http://projects.scipy.org/mailman/listinfo/nipy-devel ---> https://mail.python.org/mailman/listinfo/neuroimaging

Added links to 

* https://gitter.im/nipy/nipype
* https://brainhack.slack.com/messages/C1FR76RAL

## Acknowledgment

- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by KirstieJane** [comment]
A little ps: I'm working on a windows laptop and I can't install make so I haven't tested the docs build. Really sorry if they don't render properly 😞

**Comment by satra** [comment]
thank you @KirstieJane !

**Comment by satra** [comment]
and just as an fyi, circle does build the docs in this branch **ci/circleci: test_pytest **, so one can see the rendered docs (through the artifacts tab).

**Comment by mgxd** [comment]
@KirstieJane on [your build](https://circleci.com/gh/nipy/nipype/5953#artifacts/containers/0), you can click on the artifacts tab and expand the docs/ tree - here's a link to the [main page](https://5953-791477-gh.circle-artifacts.com/0/home/circleci/work/docs/index.html)

**Comment by KirstieJane** [comment]
Thank you @mgxd and @satra! The problem was that I wasn't signed in to circle ci - I can see most of the other tabs but *not* the artifacts one by just clicking the links you sent 😸  Once I logged in I could see that tab and all made sense ✨

**Pull request merged**
