### PR TITLE
[ENH] Improved nosetest information

### PR DESCRIPTION
**Pull request by oesteban**
I was running ```nosetests --verbosity 1 --with-doctest nipype``` and getting:
```
/home/oesteban/workspace/nipype/nipype/__init__.py:57: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
Segmentation fault
```

Applying this trick: http://reinout.vanrees.org/weblog/2013/08/15/handy-tracebacks-with-faulthandler.html, now I get:
```
/home/oesteban/workspace/nipype/nipype/__init__.py:64: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
Fatal Python error: Segmentation fault

Current thread 0x00007f631c037700 (most recent call first):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/qt_compat.py", line 91 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/formlayout.py", line 58 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5.py", line 27 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 18 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_qt4agg.py", line 17 in <module>
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32 in pylab_setup
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 109 in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/external/importtools.py", line 123 in import_module
  File "/usr/local/lib/python2.7/dist-packages/sympy/plotting/plot.py", line 40 in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/plotting/__init__.py", line 1 in <module>
  File "/usr/local/lib/python2.7/dist-packages/sympy/__init__.py", line 70 in <module>
  File "/usr/local/lib/python2.7/dist-packages/nipy/algorithms/statistics/formula/formulae.py", line 118 in <module>
  File "/usr/local/lib/python2.7/dist-packages/nipy/algorithms/statistics/formula/__init__.py", line 2 in <module>
  File "/usr/local/lib/python2.7/dist-packages/nipy/algorithms/statistics/__init__.py", line 8 in <module>
  File "/usr/local/lib/python2.7/dist-packages/nipy/algorithms/__init__.py", line 9 in <module>
  File "/home/oesteban/workspace/nipype/nipype/interfaces/nipy/utils.py", line 21 in <module>
  File "/home/oesteban/workspace/nipype/nipype/interfaces/nipy/__init__.py", line 3 in <module>
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94 in importFromDir
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47 in importFromPath
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418 in loadTestsFromName
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 191 in loadTestsFromDir
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 354 in loadTestsFromModule
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 433 in loadTestsFromName
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 191 in loadTestsFromDir
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 354 in loadTestsFromModule
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 433 in loadTestsFromName
  File "/usr/lib/python2.7/unittest/loader.py", line 130 in loadTestsFromNames
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 481 in loadTestsFromNames
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 193 in createTests
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 179 in parseArgs
  File "/usr/lib/python2.7/unittest/main.py", line 94 in __init__
  File "/usr/local/lib/python2.7/dist-packages/nose/core.py", line 121 in __init__
  File "/usr/local/bin/nosetests", line 11 in <module>
Segmentation fault
```

What is a very improved information...

### CODE REVIEW

**Comment by oesteban** [comment]
BTW anyone knows a solution to the segmentation fault?

**Comment by satra** [comment]
this seems like similar to the headless failure, and appears to be happening in matplotlib when trying to determine backends. i have not seen this till now. does it also happen you push your branch to travis?

**Comment by oesteban** [comment]
Nope, in travis it is OK

**Comment by chrisfilo** [comment]
please rebase/merge master - we have fixed the CircleCI tests

**Pull request merged**
