### PR TITLE
[WIP] Write interfaces for MRTrix3

### PR DESCRIPTION
**Pull request by oesteban**
List of executables in new MRTrix3:

- [ ] In ```bin/```:
  - [ ] 5tt2gmwmi
  - 5tt2vis
  - 5ttedit
  - [x] 5ttgen
  - [ ] afdconnectivity
  - [ ] amp2sh
  - [ ] dcmedit
  - [ ] dcminfo
  - [ ] dirflip
  - [ ] dirgen
  - [ ] dirmerge
  - [ ] dirorder
  - [ ] dirsplit
  - [ ] dirstat
  - [ ] dwi2adc
  - [x] dwi2fod
  - [x] dwi2mask
  - [ ] dwi2noise
  - [ ] dwi2qbi
  - [x] dwi2response
  - [x] dwi2tensor
  - [ ] dwiextract
  - [ ] fixel2sh
  - [ ] fixel2voxel
  - [ ] fixelmult
  - [ ] fixelthreshold
  - [ ] fod2fixel
  - [ ] gen_planar_ROI
  - [ ] label2colour
  - [x] labelconfig
  - [ ] maskfilter
  - [x] mesh2pve
  - [ ] mrcalc
  - [ ] mrcat
  - [ ] mrclusterstats
  - [ ] mrconnect
  - [ ] mrconvert
  - [ ] mrcrop
  - [ ] mrfilter
  - [ ] mrinfo
  - [ ] mrmath
  - [ ] mrresize
  - [ ] mrstats
  - [ ] mrthreshold
  - [ ] mrtransform
  - [ ] mrview
  - [ ] peaks2amp
  - [ ] sh2amp
  - [ ] sh2peaks
  - [ ] sh2power
  - [ ] sh2response
  - [ ] shbasis
  - [ ] shconv
  - [ ] shview
  - [x] tck2connectome
  - [x] tck2vtk
  - [ ] tckedit
  - [ ] tckfixcount
  - [x] tckgen
  - [ ] tckimport
  - [ ] tckinfo
  - [x] tckmap
  - [ ] tcknodeextract
  - [ ] tcknormalise
  - [ ] tcksample
  - [ ] tcksift
  - [ ] tckstats
  - [x] tensor2metric
  - [ ] transformcalc
  - [ ] tsfdivide
  - [ ] tsfinfo
  - [ ] tsfmult
  - [ ] tsfthreshold
  - [ ] warpinit
- [ ] In ```scripts/```:
  - [ ] act_anat_prepare_freesurfer
  - [x] act_anat_prepare_fsl
  - [ ] average_response
  - [ ] blend
  - [ ] convert_bruker
  - data
  - [ ] dwibiascorrect
  - foreach
  - [x] fs_parc_replace_sgm_first
  - lib
  - [ ] revpe_distcorr
  - [ ] revpe_dwicombine

### CODE REVIEW

**Comment by oesteban** [comment]
@chrisfilo @satra I was wondering your opinion about this new set of interfaces for MRTrix3. I'd also need your opinion about the new ```interfaces.mrtrix3``` module, to live besides the former mrtrix 0.2.

Regarding the features it currently contains, I think it covers enough part of MRTrix3 to merge already. What do you think of maintaining the list of binaries in the wiki and update there the ones supported?

**Comment by oesteban** [comment]
May I ask for your revision? @satra, @chrisfilo (or anyone interested in having MRTrix3 interfaces...)

Thanks a lot! :+1:

**Comment by satra** [comment]
@oesteban - i think it's fine for mrtrix3 to live beside mrtrix2. would it be possible for you to encourage the mrtrix folks to generate slicer execution model like xml files? then we could automatically generate interfaces for these tools. 

http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/SlicerExecutionModel

i'm also fine with incrementally adding mrtrix tools and having a wiki to show support. we could start doing this for the big packages in general. over the next few years, i would like to instrument external software to automatically generate specs on how to run them. that's the most scalable option.

**Comment by oesteban** [comment]
Great thanks!

I have created a new wiki page for this: https://github.com/nipy/nipype/wiki/Status-of-interfaces

I will post an issue on MRTrix github to suggest the xml descriptions :+1:

**Pull request merged**
