### PR TITLE
aded support for custom IRF in FSL models

### PR DESCRIPTION
**Pull request by TheChymera**
Two more variables need to be added - `set fmri(basisorth1) 1` and `set fmri(basisfnum1) 1`, but I am still holding out because I don't get what they do exactly (and thus, how best to manage them).

I have [asked the FSL mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1702&L=FSL&F=&S=&X=0DEDE23E0EB8FCD9BA&Y=ioanas%40biomed.ee.ethz.ch&P=191089) but gotten no reply. If you know anything about what these variables do exactly, I would be happy to know.

### CODE REVIEW

**Comment by TheChymera** [comment]
@satra can you help me figure out what failed here? The travis fail is a segfault - almost certainly unrelated to my PR. But I really can't tell what's wrong with circleCI. 

Also, how can I re-run the travis build? I have an account and I am logged in (and I have added TheChymera/nipype to my list of builds), but I still don't see a re-run button.

**Comment by djarecka** [comment]
I can restart your Travis if you want (not sure why you can't see "restart build" button), the segfault is indeed not related to your PR.

**Comment by TheChymera** [comment]
@djarecka Could you please do that? Also, any idea what's wrong with CircleCI? I can't seem to locate the fatal error message.

**Comment by effigies** [comment]
@TheChymera Merge or rebase against nipy/master. There's been some work fixing the Dockerfiles.

**Pull request merged**
