### PR TITLE
inst: ensure later versions of setuptools are used

### LINKED ISSUE #2108: Installation error
### Summary
I am trying to install nipype, but am encountering an error. I am using Python 2.7 on Windows 8.1. I ran the install as administrator with: 

`python -m pip install nipype
`
### Actual behavior
The installation runs at first but produces the following error:

```
error: can't copy 'nipype\testing\data\brukerdir\pdata': doesn't exist or not a regular file. 
         --------------------------------------------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\joseph\\appdata\\local\\temp\\pip-build-2bngm1\\nipype\\setup.py';f=geta
ttr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
e();exec(compile(code, __file__, 'exec'))" install --record c:\users\joseph\appd
ata\local\temp\pip-yvbrtb-record\install-record.txt --single-version-externally-
managed --compile" failed with error code 1 in c:\users\joseph\appdata\local\tem
p\pip-build-2bngm1\nipype\
```

### Execution environment

Windows 8.1

### PR DESCRIPTION
**Pull request by mgxd**
Fixes #2108  .

Changes proposed in this pull request
- require later versions of setuptools for installation

Objections with using `setuptools 36.6.0`?

### CODE REVIEW

**Comment by satra** [comment]
can we add an install test as part of nipype into a controlled environment?

**Comment by mgxd** [comment]
@satra I'm not sure what you mean, across various OS? (this PR seems to fix default `Ubuntu 16.04`)

**Comment by satra** [comment]
@mgxd -  before this fix is implemented can you run a test that breaks before the change is implemented. to basically a test to "test that install works" into an environment.

**Comment by mgxd** [comment]
we can actually use earlier versions - see #2280

**Pull request closed without merging**
