### PR TITLE
Fix install error

### LINKED ISSUE #1193: Unable to install latest nipype version
After cloning the latest version of nipype on github, the installation fails:

```
$ sudo python setup.py install
/usr/local/nipype/nipype/__init__.py:57: UserWarning: Running the tests from the install directory may trigger some failures
  warnings.warn('Running the tests from the install directory may '
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
package init file 'nipype/interfaces/camino2trackvis/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/cmtk/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/diffusion_toolkit/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/dipy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/elastix/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/freesurfer/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/fsl/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mipav/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mne/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/mrtrix/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/nipy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/nitime/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/script_templates/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/brains/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/diffusion/tractography/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/filtering/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/legacy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/registration/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/segmentation/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/semtools/utilities/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/filtering/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/legacy/diffusion/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/legacy/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/quantification/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/registration/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/segmentation/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/slicer/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/spm/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/interfaces/vista/tests/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/bedpostxout/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/dicomdir/__init__.py' not found (or not a regular file)
package init file 'nipype/testing/data/tbss_dir/__init__.py' not found (or not a regular file)
error: can't copy 'nipype/testing/data/tbss_dir': doesn't exist or not a regular file
```

### PR DESCRIPTION
**Pull request by chrisfilo**
Fixes #1193 by removing test data from the install. I tried many different things, but this was the only one that worked. I also moved testing instructions to dev documentation since without test data userst would not be able to run nipype.test(). This is not ideal, but being able to install nipype takes precedence over being able to test it.

### CODE REVIEW

**Comment by satra** [comment]
hold off on merging this. even if it passes. `python setup.py install works` fine on our cluster as well as `pip install` - i don't want to fix something for a very specific scenario by disabling all the smoketests. perhaps @yarikoptic has some thoughts here.

**Comment by chrisfilo** [comment]
I cannot replicate this error myself, but many users did. I had to work
with one user who stumbled on this error to make sure this solution works.

Tests will still run on Travis and CircleCI. It will be just harder for
users to run them themselves.

**Comment by chrisfilo** [comment]
All tests are passing now.

**Comment by chrisfilo** [comment]
Any thoughts?

**Comment by oesteban** [comment]
Would it be possible to remove the test data files (as you did), but when they are needed for first when running tests, generate (or download if not empty) them?.

**Comment by satra** [comment]
@oesteban - this has been fixed here: https://github.com/nipy/nipype/pull/1420

we are waiting confirmation from chris' folks.

**Comment by satra** [comment]
superceded by #1420

**Pull request closed without merging**
