### PR TITLE
CI/DOCKER: Hard code miniconda 4.3.31

### PR DESCRIPTION
**Pull request by effigies**
Travis builds on master are failing, apparently because of today's miniconda release, which bundled asn1crypto 0.24. Possibly rolling back to 0.23 will fix the issue.

### CODE REVIEW

**Comment by satra** [comment]
@effigies - perhaps it would be good to use wheels for all the installers. i think they all exist now. also i'm not sure if the icu issue is an issue still. may be worthwhile to synchronize this with the docker builds.

i think some of this comes from the time it takes to update conda forge packages.

**Comment by effigies** [comment]
I'm not really sure what would be involved in such a change. If it's non-trivial, perhaps we should discuss Thursday. The 0.23 install had the same issue, so I've tried reverting to the most recent release of Miniconda. Assuming that passes, is that an acceptable stop-gap until then?

**Comment by effigies** [comment]
(It looks to be passing.)

**Comment by effigies** [comment]
Actually, it looks like the new Miniconda is breaking the Circle builds, too. They're retrying building the Docker images. I'm going to hard code the old one there, too.

This might be worth escalating, but I'm not sure where the best place to make noise would be.

**Comment by effigies** [comment]
Okay, going to merge this to get tests passing again. I'll open a PR that reverts the hard-coding, so we can see if miniconda gets an update that fixes this, or move on to Satra's wheel installer approach.

**Pull request merged**
