### PR TITLE
Update N4BiasFieldCorrection inputs for compatibility

### PR DESCRIPTION
**Pull request by blakedewey**
Update N4BiasFieldCorrection to use short tag for compatibility with new releases as long tag has changed.

### CODE REVIEW

**Comment by satra** [comment]
@blakedewey - could you also please run `make check-before-commit` (see CONTRIBUTING.md) and then commit the changes and push. the auto tests are failing because you updated the interface.

**Comment by satra** [comment]
@blakedewey - could you please merge with current master so that tests pass?

**Comment by blakedewey** [comment]
I did as much as I could for the time being. My test setup for commits is all messed up from some playing around that I did. I will try to recreate it and upload the test/CHANGES file changes.

**Comment by blakedewey** [comment]
@satra This should be ready to go. Sorry for the delay.

**Pull request merged**
