### PR TITLE
ref: isolate function handling from __future__ imports

### PR DESCRIPTION
**Pull request by mgxd**
Re-attempt after #2148

### CODE REVIEW

**Comment by satra** [comment]
@mgxd - can you make sure master is merged into this.

**Comment by mgxd** [comment]
Yes, it is. Do you remember what error arose after merging this previously? If so, I could add a test for that.

**Comment by mgxd** [comment]
@satra pinging this again

**Comment by mgxd** [comment]
@satra let's try to get this in for 0.14

**Comment by satra** [comment]
@mgxd - can you create a milestone for 0.14, and add any issues that should be resolved for 0.14.

**Pull request merged**
