### PR TITLE
ADD class DARTELExistingTemplates to interfaces.spm

### LINKED ISSUE #2077: Issue : isn’t SPM12 “Dartel – Run Dartel (existing templates)” implemented in nipype ?
Hi,

I’ve been trying to find the Nipype implementation for the Dartel - Run Dartel (existing templates) routine from SPM12 interface to run Dartel with my own tissue map template (TPM based on MNI and extra tissue class for tumor, see m-file at the end of this message). But I only found the spm.DARTEL() function which produces its own templates and has no input parameter for existing templates.

It seems that this specific routine isn’t implemented yet, am I right ? And if so, would it be possible to adapt the Nipype implementation of Dartel to take this case into account?

Thanks for your answer,

Ariane

### SPM12 m-file for ‘Dartel – Run Dartel (Existing Templates)’:

%-----------------------------------------------------------------------
% Job saved on 18-May-2017 14:36:59 by cfg_util (rev $Rev: 6460 $)
% spm SPM - SPM12 (6906)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.tools.dartel.warp1.images = {
                                                {'rc1GLAS12008RM_05136012_3D_Gado.nii,1'}
                                                {'rc2GLAS12008RM_05136012_3D_Gado.nii,1'}
                                                }';
matlabbatch{1}.spm.tools.dartel.warp1.settings.rform = 0;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(1).its = 3;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(1).rparam = [1 0.5 1e-06];
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(1).K = 1;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(1).template = {'TPMGMWM.nii'};
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(2).its = 3;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(2).rparam = [0.5 0.25 1e-06];
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(2).K = 2;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(2).template = {'TPMGMWM.nii'};
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(3).its = 3;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(3).rparam = [0.25 0.125 1e-06];
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(3).K = 6;
matlabbatch{1}.spm.tools.dartel.warp1.settings.param(3).template = {'TPMGMWM.nii'};
matlabbatch{1}.spm.tools.dartel.warp1.settings.optim.lmreg = 0.01;
matlabbatch{1}.spm.tools.dartel.warp1.settings.optim.cyc = 3;
matlabbatch{1}.spm.tools.dartel.warp1.settings.optim.its = 3;

### Execution environment

python                    2.7.13                        1    conda-forge
nipype                    0.12.1                   py27_1    conda-forge

### PR DESCRIPTION
**Pull request by PaulineRoca**
Fixes #2077

Changes proposed in this pull request
- Add a new class DARTELExistingTemplates to interfaces.spm (and the associated test_auto* file).

This class is an API for the DARTEL batch "Run Dartel (existing Templates)

### CODE REVIEW

**Comment by mgxd** [comment]
Hi @PaulineRoca,

Thanks for contributing to Nipype! A couple comments:

* The tests are failing because `DARTELExistingTemplates` isn't included in [`spm's __init__.py`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/spm/__init__.py)
* It seems this shares a lot of similar code with the current `DARTEL` interface, perhaps adding this functionality to the older interface would be a cleaner approach. 

Let us know if you have any questions along the way!

**Comment by PaulineRoca** [comment]
Hi @mgxd,

Thanks for your quick reply.

Concerning your comments:
- I will modify my pull request to change [https://github.com/nipy/nipype/blob/master/nipype/interfaces/spm/__init__.py](url) 
- for the second point, you're right, DARTEL and DARTELExistingTemplates shares a lot code. But DARTELExistingTemplates has not the same "field" (=warp1) as DARTEL (field=warp). That's why I thought it was not possible to easily "merge" these two "Dartel" functionalities. Am I right ?

Thanks in advance for your help !

**Comment by mgxd** [comment]
@PaulineRoca currently yes, but we can try to tweak the code to make this easier.

However, a few steps are needed:
* Define a boolean input named `use_existing_template`, setting the default to False.
* Remove the 'warp.' prefix on all input's `field` assignments (ex. `image_files` goes from `field='warp.images'` to `field='images'`
* In the `DARTEL` class, modify `_jobname` to `'dartel.warp'`.
* Check `use_existing_template` when `DARTEL` is initialized, and change `_jobname` to `'dartel.warp1'`. [Here](https://github.com/nipy/nipype/blob/master/nipype/interfaces/fsl/epi.py#L566) is an example of this being down to change the `Eddy` command if the `use_cuda` boolean is `True`.

How does this sound? Feel free to ask for support if you need any!

**Comment by PaulineRoca** [comment]
Hi @mgxd,
Thanks for these explanations. It is very clear. 
I will try to do another pull request on this as soon as possible.
Thanks !

**Comment by mgxd** [comment]
@PaulineRoca just checking if you have any questions

**Comment by PaulineRoca** [comment]
@mgxd It is just a problem of lack of time for me, during next weeks I will try to take some time. Sorry for the delay...!

**Comment by effigies** [comment]
This pull request is "orphaned," which means it has been deemed to be abandoned by its original author. Orphaned pull requests have not been rejected, and we hope that if a user sees one that will meet their needs with a little work, that they will fork it and open a new pull request (or, in the case of the original author, reopen the original PR).

We ask that all adopted PRs be updated to merge or rebase the current master. If you would like to adopt a PR and need help getting started, any of a number of contributors will be happy to help.

**Pull request closed without merging**
