### PR TITLE
New bru2nii pull request

### PR DESCRIPTION
**Pull request by TheChymera**
Replaces https://github.com/nipy/nipype/pull/1425 for which the history got messed up.

### CODE REVIEW

**Comment by TheChymera** [comment]
@satra ?

**Comment by satra** [comment]
same here: `make specs`

**Comment by TheChymera** [comment]
how do I do that? I have queried for `make specs` in the source tree, and I found no examples.

**Comment by satra** [comment]
@TheChymera - it's in: https://github.com/nipy/nipype/blob/master/CONTRIBUTING.md

the `Makefile` is in the root nipype directory

**Comment by satra** [comment]
@TheChymera - can you update this one too.

**Comment by TheChymera** [comment]
why do these rebases blow up every once in a while? :-/

**Pull request closed without merging**
