### PR TITLE
fix tbss_non_FA to match FSL's tbss_non_FA command

### PR DESCRIPTION
**Pull request by psharp1289**
Here is the FSL command from their source code:
"${FSLDIR}/bin/tbss_skeleton -i mean_FA -p $thresh mean_FA_skeleton_mask_dst ${FSLDIR}/data/standard/LowerCingulum_1mm all_FA all_${ALTIM}skeletonised -a all$ALTIM"
where all_${ALTIM} in my example is all_RD. notice all_FA is in the placeholder for the 4d Data file under the -p option, and the -a all_RD is there too.
here is what I changed in tbss.py to allow for this:
see new inputnode, all_FA_file and
see (maskgroup, projectfa, [('out_file', 'alt_data_file')]) step in tbss_non_fa.connect command. This is to get the -a option with the all_RD file.

### CODE REVIEW

**Comment by satra** [comment]
@psharp1289 - could you please merge with upstream and add an updated CHANGES file?

**Comment by psharp1289** [comment]
Sure I will try to do this (again I'm new to GitHub).

Paul

On Tue, Feb 10, 2015 at 12:39 PM, Satrajit Ghosh <notifications@github.com>
wrote:

> @psharp1289 <https://github.com/psharp1289> - could you please merge with
> upstream and add an updated CHANGES file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/nipype/pull/1033#issuecomment-73745278>.
>



-- 
Paul B. Sharp
PhD Candidate, University of Illinois Urbana Champaign
http://psharp1289.wix.com/paulbsharp

**Comment by psharp1289** [comment]
I think I did it correctly this time. I went to my local branch called
"patch-1" and update the CHANGES file. Anything else I need to do?

Paul

On Tue, Feb 10, 2015 at 12:39 PM, Satrajit Ghosh <notifications@github.com>
wrote:

> @psharp1289 <https://github.com/psharp1289> - could you please merge with
> upstream and add an updated CHANGES file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nipy/nipype/pull/1033#issuecomment-73745278>.
>



-- 
Paul B. Sharp
PhD Candidate, University of Illinois Urbana Champaign
http://psharp1289.wix.com/paulbsharp

**Comment by satra** [comment]
@psharp1289 - could you copy in the latest CHANGES file (from master) and then add your change, that will help with the merge.

**Comment by psharp1289** [comment]
Ok. My CHANGES file should be identical to the master branch with my addition at the top of the file under "patch-1" branch. 

Thanks for the continued assistance. 

Paul

**Pull request merged**
