### PR TITLE
Inital commit to add niftyfit interfaces

### PR DESCRIPTION
**Pull request by byvernault**
Dear nipype team,

We are ready to add niftyfit to nipype. I copied all the interfaces we generated for this package as well as the test.

I tested it with python 2 and python 3. It's working on my computer.

Let me know if you see anything not compatible or that I should change in the code.

Kind Regards,

Ben

### CODE REVIEW

**Comment by oesteban** [comment]
Hi @byvernault all the tests seem to be passing in our settings as well. I also went through the code quickly and overall it looks really good.

We are right now in a Nipype workshop for this week so we may not find time for the deep review this deserves, but I'm sure we can get this merged over the next two weeks.

Thanks a lot, this is a really valuable contribution and I'm sure it will expose Nifty- tools to a good bunch of new users.

**Comment by byvernault** [comment]
Hi,

I think we are finally good with this branch to add niftyseg interface to nipype.

Let me know if you have any question.

Kind Regards,
Ben

**Comment by byvernault** [comment]
Hi guys,

Thank you for pulling niftyreg and niftyseg request to nipype.
I extended the few changes you recommended for niftryseg into niftyfit.

Let me know if you think there is other changes to do.

Thanks for all your help.

Kind Regards,
Ben

P.S:  BTW, do you have an idea when is the next nipype release?

**Comment by satra** [comment]
@byvernault -re: release,  i'm hoping tomorrow.

**Comment by byvernault** [comment]
@satra Great :).

Do you think you will have time to add niftyfit before the release?

Cheers,
Ben

**Comment by satra** [comment]
@byvernault - i ran into an issue with doc building - the ones already pulled in are giving a bunch of errors. i believe they are all from the docstrings, so i'm replacing this 

```
    For source code, see http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftySeg
    For Documentation, see:
        http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftySeg_documentation
```

with

```
    `Source code <http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftySeg>`_ | 
    `Documentation <http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftySeg_documentation>`_
``` 

you'll need a few more tools to build the docs: sphinx, pydotplus. and then do `make html > doc.txt 2>&1` and look for `ERROR` in `doc.txt`

**Comment by byvernault** [comment]
Oops. Ok, I will check that for niftyfit (as well as niftyreg/niftyseg) and fix those issues.

Sorry.

**Comment by byvernault** [comment]
@satra , when I build the doc, It finishes without issue on the build:

copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2768 warnings.

Build finished. The HTML pages are in _build/html.
Build HTML and API finished.

When I load the index.html and I look at niftyseg.patchmatch, I can see the docsting fine, the only thing is that I am missing a ending line after the first url.

What kind of error do you have? I am probably doing something wrong. 
I am running 'make html > doc_error.txt 2>&1' from the folder nipype/doc.

Cheers,

**Comment by satra** [comment]
@byvernault -  do `cat doc.txt | grep ERROR`.

i pushed the changes for master here: https://github.com/nipy/nipype/pull/1997

**Comment by byvernault** [comment]
Got it. I see the errors. I will edit niftyseg files to fix them in this branch. Is that fine?

I don't see any for niftyfit and niftyreg.

Do you?

**Comment by byvernault** [comment]
@satra I think I fixed all the docstring for niftyseg and I didn't see any for the other packages.

WDYT?

**Comment by satra** [comment]
@byvernault - #1997 fixes the issues with niftyseg - so you should be able to remove those from here. once that PR gets merged, i would suggest merging with master, running `make check-before-commit` and then updating this.

doesn't look like i'll be able to cut a release tonight. so sometime over the weekend.

**Comment by satra** [comment]
@byvernault  - if you could merge master and resolve the conflicts that would be great. i think you could replace niftiseg files with the one from master.

**Comment by byvernault** [comment]
Sorry, I committed from another computer and I changed the author after the commit. I though I did change it for the commit but apparently not.  

Kind Regards,
Ben

**Pull request merged**
