### PR TITLE
MRG: Updates to SGE Plugins

### PR DESCRIPTION
**Pull request by blakedewey**
PEP8 Correction. Typo and function definition cleanup. Hopefully cut down on number of qstat/qacct calls.

### CODE REVIEW

**Comment by blakedewey** [comment]
@satra and @hjmjohnson. I have made some updates to the SGE plugin that I think will help streamline qstat and qacct calls. Please look this over and verify. Has been running a few days on my cluster with no problems. @mwaskom this should also help your PEP8 wall of shame.

**Comment by satra** [comment]
@hjmjohnson - any chance you can check this? the code changes look fine to me.

**Comment by hjmjohnson** [comment]
@satra I will look at this today.  Hans

**Comment by hjmjohnson** [comment]
Job are running use SGE now.  I will review succes/failures in the morning.

**Comment by hjmjohnson** [comment]
@satra Last nights testing seemed to perform as expected.  I think this is good to merge.

**Pull request merged**
