### PR TITLE
REL: 1.2.0

### PR DESCRIPTION
**Pull request by effigies**
## Summary

Prep for 1.2.0 release, targeting Thursday, May 9. Shooting for a pretty short turnaround mostly because we overshot by about a month, but also because #2878 would be very useful to have in a published release.

If there's something you strongly want to see in 1.2.0, please add it to the [1.2.0 milestone](https://github.com/nipy/nipype/milestone/31) or respond here ASAP. We can make a pre-release tomorrow morning for the sake of depending on it on PyPI, and extend the 1.2.0 window as needed.

Otherwise, please add it to the [1.2.1 milesteone](https://github.com/nipy/nipype/milestone/31). Note that I targeted that one to late June, as this next month is going to be busy.

## Release checklist

* [x] Update changelog
* [x] Update .mailmap
* [x] Update .zenodo.json
* [x] Set release number in `nipype/info.py` and `doc/conf.py`
* [x] Update `doc/documentation.rst` with previous releases
* [x] Tutorial tests (@djarecka)

## Acknowledgment

- [x] \(Mandatory\) I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
Note that the following names don't have Zenodo entries. Please comment with your preferred info if you want to be listed as an author on Zenodo releases. Apologies if you've done this before and our script removed you. I'll update the mailmap to make sure it doesn't happen again. Please use any diacritics and initials that you would want in a publication. And if you don't have an [ORCID](https://orcid.org/), I would recommend getting one.

No entry to sort: John Lee (@leej3)
No entry to sort: Martin (@MartinPerez)
No entry to sort: Isaiah Norton (@ihnorton)
No entry to sort: Niklas Förster (@niklasfoe)
No entry to sort: daniel glen (@afni-dglen) 
No entry to sort: Matt Cieslak (@mattcieslak)
No entry to sort: Kirstie Whitaker (@KirstieJane)
No entry to sort: hstojic (@hstojic)
No entry to sort: Gio Piantoni (@gpiantoni)
No entry to sort: Jonathan R. Williford (@williford)
No entry to sort: Hao (@anbai106)
No entry to sort: Fred Mertz
No entry to sort: Kevin Sitek (@sitek)
No entry to sort: Ami Tsuchida
No entry to sort: Abel González (@abelalez)
No entry to sort: Michiel Cottaar (@MichielCottaar)
No entry to sort: Michael R. Crusoe (@mr-c)
No entry to sort: Daniel Brenner (@brennerd11)
No entry to sort: BenjaminMey (@BenjaminMey)
No entry to sort: Andrew Van (@vanandrew)

I don't think Fred Mertz is a real name, and I can't quickly find an Ami Tsuchida on GitHub, but I think I've mapped everybody else to their GitHub users. If you don't want to be listed as an author, I'll add you to an exclude list so that I don't bother you again.

**Comment by mr-c** [comment]
I'm https://orcid.org/0000-0002-2961-9670

**Comment by leej3** [comment]
Apologies for the delay. I got a zenodo account (leej3), and my orcid is https://orcid.org/0000-0001-5884-4247. Thanks

**Comment by mattcieslak** [comment]
Did I miss the window?

```
    {
      "name": "Cieslak, Matthew",
      "affiliation": "Department of Neuropsychiatry, University of Pennsylvania",
      "orcid": "0000-0002-1931-4734"
    }
```

**Comment by effigies** [comment]
Yeah, sorry about that. I'll get you both in so you'll be on the next release. Anybody else who wants to add themselves, feel free to comment.

**Comment by BenjaminMey** [comment]
{
  "affiliation": "University of Pittsburgh",
  "name": "Meyers, Benjamin",
  "orcid": "0000-0001-9137-4363"
}

**Comment by vanandrew** [comment]
My orchid link: https://orcid.org/0000-0002-8787-0943

**Pull request merged**
